### ISSUE TITLE
Converting option values to string

### ISSUE THREAD

**Issue by jedbrown** [executablebooks/MyST-Parser#289]
**Describe the bug**
Use of `code-block` with `emphasize-lines: 2` fails in MyST, but not in ReST.

````
MyST Code Block (fails)
```{code-block} python
:emphasize-lines: 2

a = True
b = 2
c = "three"
```

ReST Code Block (works)
```{eval-rst}
.. code-block:: python
   :emphasize-lines: 2

   a = True
   b = 2
   c = "three"
```
````

It works fine if we pass multiple lines, as in `:emphasize-lines: 2,3`.

**To Reproduce**
Paste above into `index.md` and run:

```console
$ make html
[...]
Exception occurred:
  File "/home/jed/phypid/web/VENV/lib/python3.9/site-packages/sphinx/util/__init__.py", line 441, in parselinenos
    parts = spec.split(',')
AttributeError: 'int' object has no attribute 'split'
The full traceback has been saved in /tmp/sphinx-err-hti5rrjs.log, if you want to report the issue to the developers.
```

<details>

```
# Sphinx version: 3.4.3
# Python version: 3.9.1 (CPython)
# Docutils version: 0.16 release
# Jinja2 version: 2.11.2
# Last messages:
#   Running Sphinx v3.4.3
#   loading pickled environment...
#   done
#   myst v0.13.1: MdParserConfig(renderer='sphinx', commonmark_only=False, dmath_allow_labels=True, dmath_allow_space=True, dmath_allow_digits=True, update_mathjax=True, enable_extensions=['deflist', 'dollarmath', 'html_image', 'linkify', 'colon_fence'], disable_syntax=[], url_schemes=('http', 'https'), heading_anchors=2, substitutions={}, sub_delimiters=['{', '}'])
#   building [mo]: targets for 0 po files that are out of date
#   building [html]: targets for 1 source files that are out of date
#   updating environment:
#   0 added, 1 changed, 0 removed
#   reading sources... [100%] index
# Loaded extensions:
#   sphinx.ext.mathjax (3.4.3) from /home/jed/phypid/web/VENV/lib/python3.9/site-packages/sphinx/ext/mathjax.py
#   sphinxcontrib.applehelp (1.0.2) from /home/jed/phypid/web/VENV/lib/python3.9/site-packages/sphinxcontrib/applehelp/__init__.py
#   sphinxcontrib.devhelp (1.0.2) from /home/jed/phypid/web/VENV/lib/python3.9/site-packages/sphinxcontrib/devhelp/__init__.py
#   sphinxcontrib.htmlhelp (1.0.3) from /home/jed/phypid/web/VENV/lib/python3.9/site-packages/sphinxcontrib/htmlhelp/__init__.py
#   sphinxcontrib.serializinghtml (1.1.4) from /home/jed/phypid/web/VENV/lib/python3.9/site-packages/sphinxcontrib/serializinghtml/__init__.py
#   sphinxcontrib.qthelp (1.0.3) from /home/jed/phypid/web/VENV/lib/python3.9/site-packages/sphinxcontrib/qthelp/__init__.py
#   alabaster (0.7.12) from /home/jed/phypid/web/VENV/lib/python3.9/site-packages/alabaster/__init__.py
#   sphinx_togglebutton (0.2.3) from /home/jed/phypid/web/VENV/lib/python3.9/site-packages/sphinx_togglebutton/__init__.py
#   myst_nb (0.11.0) from /home/jed/phypid/web/VENV/lib/python3.9/site-packages/myst_nb/__init__.py
#   sphinxcontrib.bibtex (unknown version) from /home/jed/phypid/web/VENV/lib/python3.9/site-packages/sphinxcontrib/bibtex/__init__.py
#   sphinxcontrib.katex (0.7.1) from /home/jed/phypid/web/VENV/lib/python3.9/site-packages/sphinxcontrib/katex.py
#   pydata_sphinx_theme (unknown version) from /home/jed/phypid/web/VENV/lib/python3.9/site-packages/pydata_sphinx_theme/__init__.py
Traceback (most recent call last):
  File "/home/jed/phypid/web/VENV/lib/python3.9/site-packages/sphinx/cmd/build.py", line 280, in build_main
    app.build(args.force_all, filenames)
  File "/home/jed/phypid/web/VENV/lib/python3.9/site-packages/sphinx/application.py", line 352, in build
    self.builder.build_update()
  File "/home/jed/phypid/web/VENV/lib/python3.9/site-packages/sphinx/builders/__init__.py", line 296, in build_update
    self.build(to_build,
  File "/home/jed/phypid/web/VENV/lib/python3.9/site-packages/sphinx/builders/__init__.py", line 310, in build
    updated_docnames = set(self.read())
  File "/home/jed/phypid/web/VENV/lib/python3.9/site-packages/sphinx/builders/__init__.py", line 417, in read
    self._read_serial(docnames)
  File "/home/jed/phypid/web/VENV/lib/python3.9/site-packages/sphinx/builders/__init__.py", line 438, in _read_serial
    self.read_doc(docname)
  File "/home/jed/phypid/web/VENV/lib/python3.9/site-packages/sphinx/builders/__init__.py", line 478, in read_doc
    doctree = read_doc(self.app, self.env, self.env.doc2path(docname))
  File "/home/jed/phypid/web/VENV/lib/python3.9/site-packages/sphinx/io.py", line 221, in read_doc
    pub.publish()
  File "/home/jed/phypid/web/VENV/lib/python3.9/site-packages/docutils/core.py", line 217, in publish
    self.document = self.reader.read(self.source, self.parser,
  File "/home/jed/phypid/web/VENV/lib/python3.9/site-packages/sphinx/io.py", line 126, in read
    self.parse()
  File "/home/jed/phypid/web/VENV/lib/python3.9/site-packages/docutils/readers/__init__.py", line 77, in parse
    self.parser.parse(self.input, document)
  File "/home/jed/phypid/web/VENV/lib/python3.9/site-packages/myst_nb/parser.py", line 59, in parse
    super().parse(inputstring, document=document)
  File "/home/jed/phypid/web/VENV/lib/python3.9/site-packages/myst_parser/sphinx_parser.py", line 187, in parse
    parser.render(inputstring)
  File "/home/jed/phypid/web/VENV/lib/python3.9/site-packages/markdown_it/main.py", line 258, in render
    return self.renderer.render(self.parse(src, env), self.options, env)
  File "/home/jed/phypid/web/VENV/lib/python3.9/site-packages/myst_parser/docutils_renderer.py", line 133, in render
    self.rules[f"render_{token.type}"](token)
  File "/home/jed/phypid/web/VENV/lib/python3.9/site-packages/myst_parser/docutils_renderer.py", line 391, in render_fence
    return self.render_directive(token)
  File "/home/jed/phypid/web/VENV/lib/python3.9/site-packages/myst_parser/docutils_renderer.py", line 851, in render_directive
    result = directive_instance.run()
  File "/home/jed/phypid/web/VENV/lib/python3.9/site-packages/sphinx/directives/code.py", line 137, in run
    hl_lines = parselinenos(linespec, nlines)
  File "/home/jed/phypid/web/VENV/lib/python3.9/site-packages/sphinx/util/__init__.py", line 441, in parselinenos
    parts = spec.split(',')
AttributeError: 'int' object has no attribute 'split'
```
</details>

**Environment**

- Python Version: 3.9.1
- Package versions or output of `jupyter-book --version`: MyST-Parser 0.13.1
- Operating System: Linux

**Comment by chrisjsewell** [comment]
heya, the option are read as YAML, so you can fix this by writing `:emphasize-lines: "2"`

But yeh I'll think if they should be automatically converted back to strings

**Comment by jedbrown** [comment]
Ah, thanks for the work-around. Seems they should be parsed the same way they are in ReST. Is that always as a string, or is there more logic?
