### ISSUE TITLE
readthedocs build fails when trying to use the myst-parser

### ISSUE THREAD

**Issue by Ravenwater** [executablebooks/MyST-Parser#334]
**Describe the bug**

RTD builds fails to find `myst-parser`

**To Reproduce**

1- import new rtd repo
2- use this conf.py general config section:
```
# -- General configuration ---------------------------------------------------

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = [
    'myst_parser'
]
```

**Expected behavior**

On my local system building the RTD site, the myst-parser if found, and the site builds correctly.

A link to your documentation repository: https://github.com/stillwater-sc/universal/tree/master/docs

```console
(sphinx) C:\Users\tomtz\Documents\dev\clones\universal\docs>make html
Running Sphinx v3.5.3
loading pickled environment... done
myst v0.13.5: MdParserConfig(renderer='sphinx', commonmark_only=False, dmath_allow_labels=True, dmath_allow_space=True, dmath_allow_digits=True, update_mathjax=True, enable_extensions=['dollarmath'], disable_syntax=[], url_schemes=None, heading_anchors=None, html_meta=[], footnote_transition=True, substitutions=[], sub_delimiters=['{', '}'])
building [mo]: targets for 0 po files that are out of date
building [html]: targets for 0 source files that are out of date
updating environment: 0 added, 0 changed, 0 removed
looking for now-outdated files... none found
no targets are out of date.
build succeeded.

The HTML pages are in _build\html.
```

**Environment**

- Python Version [e.g. 3.8.3]:
- Operating System: Windows 10 Pro

**Additional context**

Sphinx build failure:

```console
Running Sphinx v3.5.3
loading translations [en]... done

Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/universal/envs/latest/lib/python3.7/site-packages/sphinx/registry.py", line 417, in load_extension
    mod = import_module(extname)
  File "/home/docs/checkouts/readthedocs.org/user_builds/universal/envs/latest/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 965, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'myst_parser'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/universal/envs/latest/lib/python3.7/site-packages/sphinx/cmd/build.py", line 279, in build_main
    args.tags, args.verbosity, args.jobs, args.keep_going)
  File "/home/docs/checkouts/readthedocs.org/user_builds/universal/envs/latest/lib/python3.7/site-packages/sphinx/application.py", line 245, in __init__
    self.setup_extension(extension)
  File "/home/docs/checkouts/readthedocs.org/user_builds/universal/envs/latest/lib/python3.7/site-packages/sphinx/application.py", line 402, in setup_extension
    self.registry.load_extension(self, extname)
  File "/home/docs/checkouts/readthedocs.org/user_builds/universal/envs/latest/lib/python3.7/site-packages/sphinx/registry.py", line 421, in load_extension
    err) from err
sphinx.errors.ExtensionError: Could not import extension myst_parser (exception: No module named 'myst_parser')

Extension error:
Could not import extension myst_parser (exception: No module named 'myst_parser')
```

**Comment by chrisjsewell** [comment]
Heya, your `universal/docs/.readthedocs.yaml` needs to be at the root of your repo and also currently points to a `requirements.txt` that does not include myst-parser. 
For further information see: https://docs.readthedocs.io/en/stable/config-file/v2.html

**Comment by Ravenwater** [comment]
@chrisjsewell thank you, thank you.

![image](https://user-images.githubusercontent.com/466641/111982893-e3da3280-8adf-11eb-96b4-269496e5c77a.png)
