### ISSUE TITLE
Footnotes not rendered properly by `to_html()`

### ISSUE THREAD

**Issue by jwodder** [executablebooks/MyST-Parser#446]
### Describe the problem

As of myst-parser v0.15.2, the following behavior occurs:

```
>>> from myst_parser.main import to_html
>>> to_html("This is a foot.[^1]\n\n[^1]: And this is the note.")
'<p>This is a foot.<sup class="footnote-ref"><a href="#fn1" id="fnref1">[1]</a></sup></p>\n<><p>And this is the note.</p>\n</>'
```

Observe that the actual footnote at the end of the output is enclosed in tags with an empty/missing name.

### Steps to reproduce

Run the code given above.

### The version of Python you're using

3.9.8

### Your operating system

macOS 11.6

### Versions of your packages

`pip list`:

```
Package                       Version
----------------------------- ---------
alabaster                     0.7.12
attrs                         21.2.0
Babel                         2.9.1
certifi                       2021.10.8
charset-normalizer            2.0.7
click                         8.0.3
docutils                      0.17.1
idna                          3.3
imagesize                     1.3.0
Jinja2                        3.0.3
linkify-it-py                 1.0.2
markdown-it-py                1.1.0
MarkupSafe                    2.0.1
mdit-py-plugins               0.2.8
myst-parser                   0.15.2
packaging                     21.3
pip                           21.3.1
Pygments                      2.10.0
pyparsing                     3.0.6
pytz                          2021.3
PyYAML                        6.0
requests                      2.26.0
setuptools                    58.3.0
snowballstemmer               2.2.0
Sphinx                        4.3.0
sphinxcontrib-applehelp       1.0.2
sphinxcontrib-devhelp         1.0.2
sphinxcontrib-htmlhelp        2.0.0
sphinxcontrib-jsmath          1.0.1
sphinxcontrib-qthelp          1.0.3
sphinxcontrib-serializinghtml 1.1.5
uc-micro-py                   1.0.1
urllib3                       1.26.7
wheel                         0.37.0
```

**Comment by jwodder** [comment]
An additional wrinkle (which should possibly be reported as a separate issue): If I try to render a Markdown document with footnotes by going through docutils, like so:

```python
from docutils.core import publish_from_doctree
from myst_parser.main import to_docutils

doc = to_docutils("This is a foot.[^1]\n\n[^1]: And this is the note.")
# Printing `doc.pformat()` at this point works and shows a normal doctree with a footnote.
output = publish_from_doctree(
    doc, writer_name="html4", settings_overrides={"output_encoding": "unicode"}
)
print(output)
```

it fails with:

```
Traceback (most recent call last):
  File "/Users/jwodder/work/dev/mds/bug01.py", line 5, in <module>
    output = publish_from_doctree(
  File "/Users/jwodder/.local/virtualenvwrapper/venvs/tmp-a4487282ac36d07/lib/python3.9/site-packages/docutils/core.py", line 522, in publish_from_doctree
    return pub.publish(enable_exit_status=enable_exit_status)
  File "/Users/jwodder/.local/virtualenvwrapper/venvs/tmp-a4487282ac36d07/lib/python3.9/site-packages/docutils/core.py", line 220, in publish
    output = self.writer.write(self.document, self.destination)
  File "/Users/jwodder/.local/virtualenvwrapper/venvs/tmp-a4487282ac36d07/lib/python3.9/site-packages/docutils/writers/__init__.py", line 78, in write
    self.translate()
  File "/Users/jwodder/.local/virtualenvwrapper/venvs/tmp-a4487282ac36d07/lib/python3.9/site-packages/docutils/writers/_html_base.py", line 80, in translate
    self.document.walkabout(visitor)
  File "/Users/jwodder/.local/virtualenvwrapper/venvs/tmp-a4487282ac36d07/lib/python3.9/site-packages/docutils/nodes.py", line 227, in walkabout
    if child.walkabout(visitor):
  File "/Users/jwodder/.local/virtualenvwrapper/venvs/tmp-a4487282ac36d07/lib/python3.9/site-packages/docutils/nodes.py", line 227, in walkabout
    if child.walkabout(visitor):
  File "/Users/jwodder/.local/virtualenvwrapper/venvs/tmp-a4487282ac36d07/lib/python3.9/site-packages/docutils/nodes.py", line 219, in walkabout
    visitor.dispatch_visit(self)
  File "/Users/jwodder/.local/virtualenvwrapper/venvs/tmp-a4487282ac36d07/lib/python3.9/site-packages/docutils/nodes.py", line 2021, in dispatch_visit
    return method(node)
  File "/Users/jwodder/.local/virtualenvwrapper/venvs/tmp-a4487282ac36d07/lib/python3.9/site-packages/docutils/writers/html4css1/__init__.py", line 521, in visit_footnote_reference
    href = '#' + node['refid']
  File "/Users/jwodder/.local/virtualenvwrapper/venvs/tmp-a4487282ac36d07/lib/python3.9/site-packages/docutils/nodes.py", line 652, in __getitem__
    return self.attributes[key]
KeyError: 'refid'
```

**Comment by chrisjsewell** [comment]
This is similar to https://github.com/executablebooks/MyST-Parser/issues/447#issuecomment-974727850, in that `to_html` does not go through the full docutils "machinery", and is really only there for testing purposes

**Comment by jwodder** [comment]
@chrisjsewell No offence, but taken together with #307, it seems that `to_html()` in its current state is borderline worthless to end-users.  Unless you plan to give it feature-parity with the full docutils path (possibly by rewriting it to use that path), it seems like it would be better to completely omit it from the Read the Docs documentation so that other users aren't fooled into thinking it'll do what they want.

**Comment by chrisjsewell** [comment]
v0.16.0, now includes a docutils API/CLI, for single string/file parsing: https://myst-parser.readthedocs.io/en/latest/docutils.html, and the docs on  `to_html()` have been updated to note this.

So will close this now, but feel free to re-open if there is still an issue
