### ISSUE TITLE
`to_docutils()` fails to produce a valid document for certain constructs

### ISSUE THREAD

**Issue by jwodder** [executablebooks/MyST-Parser#447]
### Describe the problem

As of myst-parser v0.15.2, attempting to convert certain Markdown files to HTML using the following script:

```python
import sys
from docutils.core import publish_from_doctree
from myst_parser.main import to_docutils

with open(sys.argv[1]) as fp:
    doc = to_docutils(fp.read())
#print(doc.pformat())
output = publish_from_doctree(
    doc, writer_name="html4", settings_overrides={"output_encoding": "unicode"}
)
print(output)
```

fails on the `publish_from_doctree()` call with errors that indicate that the return value from `to_docutils()` is not correctly formed.  So far, I have observed this with files using footnotes, the `contents` directive, and the `sectnum` directive.

### Failure Case 1: Footnotes

Running the above script on the following input document:

```
This is a foot.[^1]

[^1]: And this is the note.
```

produces the following document tree:

```
<document source="notset">
    <paragraph>
        This is a foot.
        <footnote_reference ids="id1" refname="1">
            1
    <transition classes="footnotes">
    <footnote ids="id2" names="1">
        <label>
            1
        <paragraph>
            And this is the note.
```

which fails to render with the following error:

```
Traceback (most recent call last):
  File "/Users/jwodder/work/dev/myst/via-docs.py", line 8, in <module>
    output = publish_from_doctree(
  File "/Users/jwodder/.local/virtualenvwrapper/venvs/myst/lib/python3.9/site-packages/docutils/core.py", line 522, in publish_from_doctree
    return pub.publish(enable_exit_status=enable_exit_status)
  File "/Users/jwodder/.local/virtualenvwrapper/venvs/myst/lib/python3.9/site-packages/docutils/core.py", line 220, in publish
    output = self.writer.write(self.document, self.destination)
  File "/Users/jwodder/.local/virtualenvwrapper/venvs/myst/lib/python3.9/site-packages/docutils/writers/__init__.py", line 78, in write
    self.translate()
  File "/Users/jwodder/.local/virtualenvwrapper/venvs/myst/lib/python3.9/site-packages/docutils/writers/_html_base.py", line 80, in translate
    self.document.walkabout(visitor)
  File "/Users/jwodder/.local/virtualenvwrapper/venvs/myst/lib/python3.9/site-packages/docutils/nodes.py", line 227, in walkabout
    if child.walkabout(visitor):
  File "/Users/jwodder/.local/virtualenvwrapper/venvs/myst/lib/python3.9/site-packages/docutils/nodes.py", line 227, in walkabout
    if child.walkabout(visitor):
  File "/Users/jwodder/.local/virtualenvwrapper/venvs/myst/lib/python3.9/site-packages/docutils/nodes.py", line 219, in walkabout
    visitor.dispatch_visit(self)
  File "/Users/jwodder/.local/virtualenvwrapper/venvs/myst/lib/python3.9/site-packages/docutils/nodes.py", line 2021, in dispatch_visit
    return method(node)
  File "/Users/jwodder/.local/virtualenvwrapper/venvs/myst/lib/python3.9/site-packages/docutils/writers/html4css1/__init__.py", line 521, in visit_footnote_reference
    href = '#' + node['refid']
  File "/Users/jwodder/.local/virtualenvwrapper/venvs/myst/lib/python3.9/site-packages/docutils/nodes.py", line 652, in __getitem__
    return self.attributes[key]
KeyError: 'refid'
```

Compare the doctree to the result of running `rst2pseudo.xml` on the equivalent reStructuredText document:

```rst
This is a foot. [1]_

.. [1] And this is the note.
```

which results in:

```
<document source="footnote.rst">
    <paragraph>
        This is a foot. 
        <footnote_reference ids="id1" refid="id2">
            1
    <footnote backrefs="id1" ids="id2" names="1">
        <label>
            1
        <paragraph>
            And this is the note.
```

### Failure Case 2: Contents

Running the above script on the following input document:

````
```{contents}
```

Apples
======
Text goes here.

Bananas
=======
Text goes here.

Coconuts
========
Text goes here.
````

produces the following document tree:

```
<document source="notset">
    <topic classes="contents" ids="contents" names="contents">
        <title>
            Contents
        <pending>
            .. internal attributes:
                 .transform: docutils.transforms.parts.Contents
                 .details:
    <section classes="tex2jax_ignore mathjax_ignore" ids="apples" names="apples">
        <title>
            Apples
        <paragraph>
            Text goes here.
    <section classes="tex2jax_ignore mathjax_ignore" ids="bananas" names="bananas">
        <title>
            Bananas
        <paragraph>
            Text goes here.
    <section classes="tex2jax_ignore mathjax_ignore" ids="coconuts" names="coconuts">
        <title>
            Coconuts
        <paragraph>
            Text goes here.
```

which fails to render with the following error:

```
Traceback (most recent call last):
  File "/Users/jwodder/work/dev/myst/via-docs.py", line 8, in <module>
    output = publish_from_doctree(
  File "/Users/jwodder/.local/virtualenvwrapper/venvs/myst/lib/python3.9/site-packages/docutils/core.py", line 522, in publish_from_doctree
    return pub.publish(enable_exit_status=enable_exit_status)
  File "/Users/jwodder/.local/virtualenvwrapper/venvs/myst/lib/python3.9/site-packages/docutils/core.py", line 220, in publish
    output = self.writer.write(self.document, self.destination)
  File "/Users/jwodder/.local/virtualenvwrapper/venvs/myst/lib/python3.9/site-packages/docutils/writers/__init__.py", line 78, in write
    self.translate()
  File "/Users/jwodder/.local/virtualenvwrapper/venvs/myst/lib/python3.9/site-packages/docutils/writers/_html_base.py", line 80, in translate
    self.document.walkabout(visitor)
  File "/Users/jwodder/.local/virtualenvwrapper/venvs/myst/lib/python3.9/site-packages/docutils/nodes.py", line 227, in walkabout
    if child.walkabout(visitor):
  File "/Users/jwodder/.local/virtualenvwrapper/venvs/myst/lib/python3.9/site-packages/docutils/nodes.py", line 227, in walkabout
    if child.walkabout(visitor):
  File "/Users/jwodder/.local/virtualenvwrapper/venvs/myst/lib/python3.9/site-packages/docutils/nodes.py", line 219, in walkabout
    visitor.dispatch_visit(self)
  File "/Users/jwodder/.local/virtualenvwrapper/venvs/myst/lib/python3.9/site-packages/docutils/nodes.py", line 2021, in dispatch_visit
    return method(node)
  File "/Users/jwodder/.local/virtualenvwrapper/venvs/myst/lib/python3.9/site-packages/docutils/nodes.py", line 2044, in unknown_visit
    raise NotImplementedError(
NotImplementedError: <class 'docutils.writers.html4css1.HTMLTranslator'> visiting unknown node type: pending
```

Compare the doctree to the result of running `rst2pseudo.xml` on the equivalent reStructuredText document:

```rst
.. contents::

Apples
======
Text goes here.

Bananas
=======
Text goes here.

Coconuts
========
Text goes here.
```

which results in:

```
<document source="contents.rst">
    <topic classes="contents" ids="contents" names="contents">
        <title>
            Contents
        <bullet_list>
            <list_item>
                <paragraph>
                    <reference ids="id1" refid="apples">
                        Apples
            <list_item>
                <paragraph>
                    <reference ids="id2" refid="bananas">
                        Bananas
            <list_item>
                <paragraph>
                    <reference ids="id3" refid="coconuts">
                        Coconuts
    <section ids="apples" names="apples">
        <title refid="id1">
            Apples
        <paragraph>
            Text goes here.
    <section ids="bananas" names="bananas">
        <title refid="id2">
            Bananas
        <paragraph>
            Text goes here.
    <section ids="coconuts" names="coconuts">
        <title refid="id3">
            Coconuts
        <paragraph>
            Text goes here.
```

### Failure Case 3: Section Numbering

Running the above script on the following input document:

````
```{sectnum}
```

Apples
======
Text goes here.

Bananas
=======
Text goes here.

Coconuts
========
Text goes here.
````

produces the following document tree:

```
<document source="notset">
    <pending>
        .. internal attributes:
             .transform: docutils.transforms.parts.SectNum
             .details:
    <section classes="tex2jax_ignore mathjax_ignore" ids="apples" names="apples">
        <title>
            Apples
        <paragraph>
            Text goes here.
    <section classes="tex2jax_ignore mathjax_ignore" ids="bananas" names="bananas">
        <title>
            Bananas
        <paragraph>
            Text goes here.
    <section classes="tex2jax_ignore mathjax_ignore" ids="coconuts" names="coconuts">
        <title>
            Coconuts
        <paragraph>
            Text goes here.
```

which fails to render with the following error:

```
Traceback (most recent call last):
  File "/Users/jwodder/work/dev/myst/via-docs.py", line 8, in <module>
    output = publish_from_doctree(
  File "/Users/jwodder/.local/virtualenvwrapper/venvs/myst/lib/python3.9/site-packages/docutils/core.py", line 522, in publish_from_doctree
    return pub.publish(enable_exit_status=enable_exit_status)
  File "/Users/jwodder/.local/virtualenvwrapper/venvs/myst/lib/python3.9/site-packages/docutils/core.py", line 220, in publish
    output = self.writer.write(self.document, self.destination)
  File "/Users/jwodder/.local/virtualenvwrapper/venvs/myst/lib/python3.9/site-packages/docutils/writers/__init__.py", line 78, in write
    self.translate()
  File "/Users/jwodder/.local/virtualenvwrapper/venvs/myst/lib/python3.9/site-packages/docutils/writers/_html_base.py", line 80, in translate
    self.document.walkabout(visitor)
  File "/Users/jwodder/.local/virtualenvwrapper/venvs/myst/lib/python3.9/site-packages/docutils/nodes.py", line 227, in walkabout
    if child.walkabout(visitor):
  File "/Users/jwodder/.local/virtualenvwrapper/venvs/myst/lib/python3.9/site-packages/docutils/nodes.py", line 219, in walkabout
    visitor.dispatch_visit(self)
  File "/Users/jwodder/.local/virtualenvwrapper/venvs/myst/lib/python3.9/site-packages/docutils/nodes.py", line 2021, in dispatch_visit
    return method(node)
  File "/Users/jwodder/.local/virtualenvwrapper/venvs/myst/lib/python3.9/site-packages/docutils/nodes.py", line 2044, in unknown_visit
    raise NotImplementedError(
NotImplementedError: <class 'docutils.writers.html4css1.HTMLTranslator'> visiting unknown node type: pending
```

Compare the doctree to the result of running `rst2pseudo.xml` on the equivalent reStructuredText document:

```rst
.. sectnum::

Apples
======
Text goes here.

Bananas
=======
Text goes here.

Coconuts
========
Text goes here.
```

which results in:

```
<document source="sectnum.rst">
    <section ids="apples" names="apples">
        <title auto="1">
            <generated classes="sectnum">
                1   
            Apples
        <paragraph>
            Text goes here.
    <section ids="bananas" names="bananas">
        <title auto="1">
            <generated classes="sectnum">
                2   
            Bananas
        <paragraph>
            Text goes here.
    <section ids="coconuts" names="coconuts">
        <title auto="1">
            <generated classes="sectnum">
                3   
            Coconuts
        <paragraph>
            Text goes here.
```

### Steps to reproduce

See above.

### The version of Python you're using

3.9.8

### Your operating system

macOS 11.6

### Versions of your packages

`pip list`:

```
Package                       Version
----------------------------- ---------
alabaster                     0.7.12
attrs                         21.2.0
Babel                         2.9.1
certifi                       2021.10.8
charset-normalizer            2.0.7
click                         8.0.3
docutils                      0.17.1
idna                          3.3
imagesize                     1.3.0
Jinja2                        3.0.3
linkify-it-py                 1.0.2
markdown-it-py                1.1.0
MarkupSafe                    2.0.1
mdit-py-plugins               0.2.8
myst-parser                   0.15.2
packaging                     21.3
pip                           21.3.1
Pygments                      2.10.0
pyparsing                     3.0.6
pytz                          2021.3
PyYAML                        6.0
requests                      2.26.0
setuptools                    58.3.0
snowballstemmer               2.2.0
Sphinx                        4.3.0
sphinxcontrib-applehelp       1.0.2
sphinxcontrib-devhelp         1.0.2
sphinxcontrib-htmlhelp        2.0.0
sphinxcontrib-jsmath          1.0.1
sphinxcontrib-qthelp          1.0.3
sphinxcontrib-serializinghtml 1.1.5
uc-micro-py                   1.0.1
urllib3                       1.26.7
wheel                         0.37.0
```

**Comment by chrisjsewell** [comment]
Heya, as noted in the `to_docutils` docstring, this function creates the docutils AST without running any transforms/post-transforms on the AST (see https://docutils.sourceforge.io/docs/ref/transforms.html), which are required before passing to `publish_from_doctree`.

This is why you see different AST with `rst2pseudo`, because it is the AST after transforms have been applied.

`to_docutils` is really mainly for testing purposes, rather than "production"

Note there is work ongoing, to improve direct use with docutils (as opposed to via sphinx) e.g. #426, which I hope to finalise in the coming month

**Comment by chrisjsewell** [comment]
So I will close this for now if thats ok, but feel free to re-open if you feel there is still an issue, or propose any improvements thanks

**Comment by jwodder** [comment]
@chrisjsewell I don't think hiding details about exactly how `to_docutils()` works in the docstring — when that docstring is absent from the Read the Docs documentation — is such a hot idea.  It would be better if this information was present somewhere under <https://myst-parser.readthedocs.io/en/latest/api/index.html>, along with a note about it being mainly for testing purposes.
