### ISSUE TITLE
0.17.1: sphinx fails because it cannot find `myst_parser` module

### ISSUE THREAD

**Issue by kloczek** [executablebooks/MyST-Parser#556]
### Describe the bug

**context**
I'm trying to build `MyST-Parser` documentation.

**expectation**
sphinx-build should not fail.

```console
[tkloczko@devel-g2v MyST-Parser-0.17.1]$ /usr/bin/sphinx-build -n -T -b man docs build/sphinx/man
Running Sphinx v4.5.0

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/sphinx/config.py", line 332, in eval_config_file
    exec(code, namespace)
  File "/home/tkloczko/rpmbuild/BUILD/MyST-Parser-0.17.1/docs/conf.py", line 10, in <module>
    from myst_parser import __version__
ModuleNotFoundError: No module named 'myst_parser'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/sphinx/cmd/build.py", line 272, in build_main
    app = Sphinx(args.sourcedir, args.confdir, args.outputdir,
  File "/usr/lib/python3.8/site-packages/sphinx/application.py", line 202, in __init__
    self.config = Config.read(self.confdir, confoverrides or {}, self.tags)
  File "/usr/lib/python3.8/site-packages/sphinx/config.py", line 165, in read
    namespace = eval_config_file(filename, tags)
  File "/usr/lib/python3.8/site-packages/sphinx/config.py", line 345, in eval_config_file
    raise ConfigError(msg % traceback.format_exc()) from exc
sphinx.errors.ConfigError: There is a programmable error in your configuration file:

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/sphinx/config.py", line 332, in eval_config_file
    exec(code, namespace)
  File "/home/tkloczko/rpmbuild/BUILD/MyST-Parser-0.17.1/docs/conf.py", line 10, in <module>
    from myst_parser import __version__
ModuleNotFoundError: No module named 'myst_parser'


Configuration error:
There is a programmable error in your configuration file:

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/sphinx/config.py", line 332, in eval_config_file
    exec(code, namespace)
  File "/home/tkloczko/rpmbuild/BUILD/MyST-Parser-0.17.1/docs/conf.py", line 10, in <module>
    from myst_parser import __version__
ModuleNotFoundError: No module named 'myst_parser'
```
```console
[tkloczko@devel-g2v MyST-Parser-0.17.1]$ make -C docs man
make: Entering directory '/home/tkloczko/rpmbuild/BUILD/MyST-Parser-0.17.1/docs'
Running Sphinx v4.5.0

Configuration error:
There is a programmable error in your configuration file:

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/sphinx/config.py", line 332, in eval_config_file
    exec(code, namespace)
  File "/home/tkloczko/rpmbuild/BUILD/MyST-Parser-0.17.1/docs/conf.py", line 10, in <module>
    from myst_parser import __version__
ModuleNotFoundError: No module named 'myst_parser'

make: *** [Makefile:20: man] Error 2
make: Leaving directory '/home/tkloczko/rpmbuild/BUILD/MyST-Parser-0.17.1/docs'
```

### Reproduce the bug

run ` make -C docs man` or `sphinx-build -n -T -b man docs` in root source tree.

### List your environment

List of modules installed in build env
```console
Package                       Version
----------------------------- -----------------
alabaster                     0.7.12
attrs                         21.4.0
Babel                         2.9.1
beautifulsoup4                4.10.0
build                         0.7.0
charset-normalizer            2.0.12
codespell                     2.1.0
cycler                        0.11.0
distro                        1.7.0
docutils                      0.17.1
extras                        1.0.0
fixtures                      3.0.0
flit_core                     3.7.1
fonttools                     4.32.0
gpg                           1.17.1-unknown
idna                          3.3
imagesize                     1.3.0
importlib-metadata            4.11.3
iniconfig                     1.1.1
Jinja2                        3.1.1
kiwisolver                    1.3.2
latexcodec                    2.0.1
libcomps                      0.1.18
linkify-it-py                 1.0.3
markdown-it-py                2.0.1
MarkupSafe                    2.1.1
matplotlib                    3.5.1
mdit-py-plugins               0.3.0
mdurl                         0.1.0
numpy                         1.22.3
olefile                       0.46
packaging                     21.3
pbr                           5.8.1
pep517                        0.12.0
Pillow                        9.1.0
pip                           22.0.4
pluggy                        1.0.0
py                            1.11.0
pybtex                        0.24.0
pybtex-docutils               1.0.1
Pygments                      2.11.2
PyGObject                     3.42.0
pyparsing                     3.0.8
pytest                        7.1.1
pytest-datadir                1.3.1
pytest_param_files            0.3.4
pytest-regressions            2.3.1
python-dateutil               2.8.2
pytz                          2022.1
PyYAML                        6.0
requests                      2.27.1
rpm                           4.17.0
six                           1.16.0
snowballstemmer               2.2.0
soupsieve                     2.3.2.post1
Sphinx                        4.5.0.dev20220404
sphinx-panels                 0.6.0
sphinxcontrib-applehelp       1.0.2.dev20220410
sphinxcontrib-bibtex          2.4.2
sphinxcontrib-devhelp         1.0.2.dev20220410
sphinxcontrib-htmlhelp        2.0.0
sphinxcontrib-jsmath          1.0.1.dev20220410
sphinxcontrib-mermaid         0.7.1
sphinxcontrib-qthelp          1.0.3.dev20220410
sphinxcontrib-serializinghtml 1.1.5
sphinxext-opengraph           0.6.3
sphinxext-rediraffe           main
testtools                     2.5.0
tomli                         2.0.1
typing_extensions             4.1.1
uc-micro-py                   1.0.1
urllib3                       1.26.9
wheel                         0.37.1
zipp                          3.8.0
```

**Comment by kloczek** [comment]
Looks like autodoc cannot find module and it fails.
With proper autodoc setup in conf.py using tox would be not necessary.

**Comment by kloczek** [comment]
With patch
```patch
--- a/docs/conf.py~     2022-04-15 11:49:57.000000000 +0000
+++ b/docs/conf.py      2022-04-15 12:03:08.377016825 +0000
@@ -4,6 +4,11 @@
 # list see the documentation:
 # https://www.sphinx-doc.org/en/master/usage/configuration.html

+import sys
+import os
+sys.path.append(os.path.abspath('..'))
+
+
 from sphinx.application import Sphinx
 from sphinx.util.docutils import SphinxDirective
```
Sphinx starrts however it crashes later with
```console
[tkloczko@devel-g2v MyST-Parser-0.17.1]$ /usr/bin/sphinx-build -n -T -b man docs build/sphinx/man
Running Sphinx v4.5.0
loading translations [en]... done
making output directory... done
checking bibtex cache... out of date
parsing bibtex file /home/tkloczko/rpmbuild/BUILD/MyST-Parser-0.17.1/docs/examples/references.bib... parsed 1 entries
myst v0.17.1: MdParserConfig(commonmark_only=False, gfm_only=False, enable_extensions=['dollarmath', 'amsmath', 'deflist', 'fieldlist', 'html_admonition', 'html_image', 'colon_fence', 'smartquotes', 'replacements', 'linkify', 'strikethrough', 'substitution', 'tasklist'], linkify_fuzzy_links=True, dmath_allow_labels=True, dmath_allow_space=True, dmath_allow_digits=True, dmath_double_inline=True, update_mathjax=True, mathjax_classes='tex2jax_process|mathjax_process|math|output_area', disable_syntax=[], all_links_external=False, url_schemes=['http', 'https', 'mailto', 'ftp'], ref_domains=None, highlight_code_blocks=True, number_code_blocks=['typescript'], title_to_header=False, heading_anchors=2, heading_slug_func=None, html_meta=[], footnote_transition=True, substitutions=[], sub_delimiters=['{', '}'], words_per_minute=200)
loading intersphinx inventory from https://docs.python.org/3.7/objects.inv...
loading intersphinx inventory from https://www.sphinx-doc.org/en/master/objects.inv...
loading intersphinx inventory from https://markdown-it-py.readthedocs.io/en/latest/objects.inv...
building [mo]: targets for 0 po files that are out of date
building [man]: all manpages
updating environment: [new config] 28 added, 0 changed, 0 removed
reading sources... [100%] syntax/syntax
/home/tkloczko/rpmbuild/BUILD/MyST-Parser-0.17.1/docs/sphinx/intro.md:102: ERROR: Unknown directive type "margin".
looking for now-outdated files... none found
pickling environment... done
checking consistency... done
writing... python-myst-parser.3 { sphinx/intro syntax/syntax syntax/optional syntax/reference explain/index sphinx/index sphinx/use sphinx/roles-and-directives sphinx/reference sphinx/faq docutils api/index api/parsers api/renderers api/reference develop/index develop/contributing develop/architecture develop/test_infrastructure examples/index examples/wealth_dynamics_rst examples/wealth_dynamics_md develop/_changelog } failed

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/sphinx/cmd/build.py", line 276, in build_main
    app.build(args.force_all, filenames)
  File "/usr/lib/python3.8/site-packages/sphinx/application.py", line 330, in build
    self.builder.build_update()
  File "/usr/lib/python3.8/site-packages/sphinx/builders/__init__.py", line 283, in build_update
    self.build(['__all__'], to_build)
  File "/usr/lib/python3.8/site-packages/sphinx/builders/__init__.py", line 350, in build
    self.write(docnames, list(updated_docnames), method)
  File "/usr/lib/python3.8/site-packages/sphinx/util/__init__.py", line 540, in wrapper
    return f(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/sphinx/builders/manpage.py", line 93, in write
    docwriter.write(largetree, destination)
  File "/usr/lib/python3.8/site-packages/docutils/writers/__init__.py", line 78, in write
    self.translate()
  File "/usr/lib/python3.8/site-packages/sphinx/writers/manpage.py", line 29, in translate
    visitor = self.builder.create_translator(self.document, self.builder)
  File "/usr/lib/python3.8/site-packages/sphinx/builders/__init__.py", line 120, in create_translator
    return self.app.registry.create_translator(self, *args)
  File "/usr/lib/python3.8/site-packages/sphinx/registry.py", line 342, in create_translator
    setattr(translator, 'visit_' + name, MethodType(visit, translator))
TypeError: first argument must be callable

Exception occurred:
  File "/usr/lib/python3.8/site-packages/sphinx/registry.py", line 342, in create_translator
    setattr(translator, 'visit_' + name, MethodType(visit, translator))
TypeError: first argument must be callable
The full traceback has been saved in /tmp/sphinx-err-d0c2vmsy.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
```
``console
[tkloczko@devel-g2v MyST-Parser-0.17.1]$ cat /tmp/sphinx-err-d0c2vmsy.log
# Sphinx version: 4.5.0
# Python version: 3.8.13 (CPython)
# Docutils version: 0.17.1 release
# Jinja2 version: 3.1.1
# Last messages:
#   develop/index
#   develop/contributing
#   develop/architecture
#   develop/test_infrastructure
#   examples/index
#   examples/wealth_dynamics_rst
#   examples/wealth_dynamics_md
#   develop/_changelog
#   }
#   failed
# Loaded extensions:
#   sphinx.ext.mathjax (4.5.0) from /usr/lib/python3.8/site-packages/sphinx/ext/mathjax.py
#   sphinxcontrib.applehelp (1.0.2) from /usr/lib/python3.8/site-packages/sphinxcontrib/applehelp/__init__.py
#   sphinxcontrib.devhelp (1.0.2) from /usr/lib/python3.8/site-packages/sphinxcontrib/devhelp/__init__.py
#   sphinxcontrib.htmlhelp (2.0.0) from /usr/lib/python3.8/site-packages/sphinxcontrib/htmlhelp/__init__.py
#   sphinxcontrib.serializinghtml (1.1.5) from /usr/lib/python3.8/site-packages/sphinxcontrib/serializinghtml/__init__.py
#   sphinxcontrib.qthelp (1.0.3) from /usr/lib/python3.8/site-packages/sphinxcontrib/qthelp/__init__.py
#   alabaster (0.7.12) from /usr/lib/python3.8/site-packages/alabaster/__init__.py
#   myst_parser (0.17.1) from /home/tkloczko/rpmbuild/BUILD/MyST-Parser-0.17.1/myst_parser/__init__.py
#   sphinx.ext.autodoc.preserve_defaults (1.0) from /usr/lib/python3.8/site-packages/sphinx/ext/autodoc/preserve_defaults.py
#   sphinx.ext.autodoc.type_comment (4.5.0) from /usr/lib/python3.8/site-packages/sphinx/ext/autodoc/type_comment.py
#   sphinx.ext.autodoc (4.5.0) from /usr/lib/python3.8/site-packages/sphinx/ext/autodoc/__init__.py
#   sphinx.ext.intersphinx (4.5.0) from /usr/lib/python3.8/site-packages/sphinx/ext/intersphinx.py
#   sphinx.ext.viewcode (4.5.0) from /usr/lib/python3.8/site-packages/sphinx/ext/viewcode.py
#   sphinxcontrib.bibtex (2.4.2) from /usr/lib/python3.8/site-packages/sphinxcontrib/bibtex/__init__.py
#   sphinx_panels (0.6.0) from /usr/lib/python3.8/site-packages/sphinx_panels/__init__.py
#   sphinxext.rediraffe (unknown version) from /usr/lib/python3.8/site-packages/sphinxext/rediraffe.py
#   sphinxcontrib.mermaid (4.5.0) from /usr/lib/python3.8/site-packages/sphinxcontrib/mermaid.py
#   sphinxext.opengraph (unknown version) from /usr/lib/python3.8/site-packages/sphinxext/opengraph/__init__.py
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/sphinx/cmd/build.py", line 276, in build_main
    app.build(args.force_all, filenames)
  File "/usr/lib/python3.8/site-packages/sphinx/application.py", line 330, in build
    self.builder.build_update()
  File "/usr/lib/python3.8/site-packages/sphinx/builders/__init__.py", line 283, in build_update
    self.build(['__all__'], to_build)
  File "/usr/lib/python3.8/site-packages/sphinx/builders/__init__.py", line 350, in build
    self.write(docnames, list(updated_docnames), method)
  File "/usr/lib/python3.8/site-packages/sphinx/util/__init__.py", line 540, in wrapper
    return f(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/sphinx/builders/manpage.py", line 93, in write
    docwriter.write(largetree, destination)
  File "/usr/lib/python3.8/site-packages/docutils/writers/__init__.py", line 78, in write
    self.translate()
  File "/usr/lib/python3.8/site-packages/sphinx/writers/manpage.py", line 29, in translate
    visitor = self.builder.create_translator(self.document, self.builder)
  File "/usr/lib/python3.8/site-packages/sphinx/builders/__init__.py", line 120, in create_translator
    return self.app.registry.create_translator(self, *args)
  File "/usr/lib/python3.8/site-packages/sphinx/registry.py", line 342, in create_translator
    setattr(translator, 'visit_' + name, MethodType(visit, translator))
TypeError: first argument must be callable
```

**Comment by kloczek** [comment]
After commenting out `sphinx_panels` I was able to make dcumentation without crash.
```python
extensions = [
    "myst_parser",
    "sphinx.ext.autodoc",
    "sphinx.ext.intersphinx",
    "sphinx.ext.viewcode",
    "sphinxcontrib.bibtex",
#    "sphinx_panels",
    "sphinxext.rediraffe",
    "sphinxcontrib.mermaid",
    "sphinxext.opengraph",
]
```
Looks like sometning may be wrong in tat extension.
```console
[tkloczko@devel-g2v MyST-Parser-0.17.1]$ /usr/bin/sphinx-build -n -T -b man docs build/sphinx/man                                                                           Running Sphinx v4.5.0
loading translations [en]... done
making output directory... done
checking bibtex cache... out of date
parsing bibtex file /home/tkloczko/rpmbuild/BUILD/MyST-Parser-0.17.1/docs/examples/references.bib... parsed 1 entries
myst v0.17.1: MdParserConfig(commonmark_only=False, gfm_only=False, enable_extensions=['dollarmath', 'amsmath', 'deflist', 'fieldlist', 'html_admonition', 'html_image', 'colon_fence', 'smartquotes', 'replacements', 'linkify', 'strikethrough', 'substitution', 'tasklist'], linkify_fuzzy_links=True, dmath_allow_labels=True, dmath_allow_space=True, dmath_allow_digits=True, dmath_double_inline=True, update_mathjax=True, mathjax_classes='tex2jax_process|mathjax_process|math|output_area', disable_syntax=[], all_links_external=False, url_schemes=['http', 'https', 'mailto', 'ftp'], ref_domains=None, highlight_code_blocks=True, number_code_blocks=['typescript'], title_to_header=False, heading_anchors=2, heading_slug_func=None, html_meta=[], footnote_transition=True, substitutions=[], sub_delimiters=['{', '}'], words_per_minute=200)
loading intersphinx inventory from https://docs.python.org/3.7/objects.inv...
loading intersphinx inventory from https://www.sphinx-doc.org/en/master/objects.inv...
loading intersphinx inventory from https://markdown-it-py.readthedocs.io/en/latest/objects.inv...
building [mo]: targets for 0 po files that are out of date
building [man]: all manpages
updating environment: [new config] 28 added, 0 changed, 0 removed
reading sources... [100%] syntax/syntax
/home/tkloczko/rpmbuild/BUILD/MyST-Parser-0.17.1/docs/docutils.md:33: ERROR: Unknown directive type "dropdown".
/home/tkloczko/rpmbuild/BUILD/MyST-Parser-0.17.1/docs/examples/index.md:22: ERROR: Unknown directive type "tabbed".
/home/tkloczko/rpmbuild/BUILD/MyST-Parser-0.17.1/docs/examples/index.md:28: ERROR: Unknown directive type "tabbed".
/home/tkloczko/rpmbuild/BUILD/MyST-Parser-0.17.1/docs/index.md:10: ERROR: Unknown directive type "panels".
/home/tkloczko/rpmbuild/BUILD/MyST-Parser-0.17.1/docs/index.md:53: ERROR: Unknown directive type "panels".
/home/tkloczko/rpmbuild/BUILD/MyST-Parser-0.17.1/docs/sphinx/intro.md:102: ERROR: Unknown directive type "margin".
/home/tkloczko/rpmbuild/BUILD/MyST-Parser-0.17.1/docs/syntax/optional.md:307: ERROR: Unknown directive type "tabbed".
/home/tkloczko/rpmbuild/BUILD/MyST-Parser-0.17.1/docs/syntax/optional.md:324: ERROR: Unknown directive type "tabbed".
/home/tkloczko/rpmbuild/BUILD/MyST-Parser-0.17.1/docs/syntax/optional.md:410: ERROR: Unknown directive type "tabbed".
/home/tkloczko/rpmbuild/BUILD/MyST-Parser-0.17.1/docs/syntax/optional.md:428: ERROR: Unknown directive type "tabbed".
/home/tkloczko/rpmbuild/BUILD/MyST-Parser-0.17.1/docs/syntax/syntax.md:432: ERROR: Unknown directive type "tabbed".
/home/tkloczko/rpmbuild/BUILD/MyST-Parser-0.17.1/docs/syntax/syntax.md:446: ERROR: Unknown directive type "tabbed".
/home/tkloczko/rpmbuild/BUILD/MyST-Parser-0.17.1/docs/syntax/syntax.md:460: ERROR: Unknown directive type "tabbed".
/home/tkloczko/rpmbuild/BUILD/MyST-Parser-0.17.1/docs/syntax/syntax.md:472: ERROR: Unknown directive type "tabbed".
looking for now-outdated files... none found
pickling environment... done
checking consistency... done
writing... python-myst-parser.3 { sphinx/intro syntax/syntax syntax/optional syntax/reference explain/index sphinx/index sphinx/use sphinx/roles-and-directives sphinx/reference sphinx/faq docutils api/index api/parsers api/renderers api/reference develop/index develop/contributing develop/architecture develop/test_infrastructure examples/index examples/wealth_dynamics_rst examples/wealth_dynamics_md develop/_changelog } done
build succeeded, 14 warnings.

The manual pages are in build/sphinx/man.
rediraffe: Redirect generation skipped for unsupported builders. Supported builders: html, dirhtml, readthedocs, readthedocsdirhtml.
```
So definitelly that path addinf proper path to `myst_parser` module is necessary and without that is not necesary to use `tox` to generate documentation in venv. As long as `sphinx.ext.autodoc` is used separated `sphinx-autobuild` execution like it is in tox.ini is not necessary.

**Comment by chrisjsewell** [comment]
See https://github.com/executablebooks/MyST-NB/issues/400#issuecomment-1100694112
