### ISSUE TITLE
0.18.0: sphinx fails

### ISSUE THREAD

**Issue by kloczek** [executablebooks/MyST-Parser#582]
### Describe the bug

I'm building `MyST-Parser` docuemtation using `sphinx-build` command.

After remove use `sphinx-design` module (becaus it is now uselesa with sphinx 5)
```patch
--- a/docs/conf.py~     2022-06-07 20:11:42.000000000 +0000
+++ b/docs/conf.py      2022-06-07 20:18:43.861023971 +0000
@@ -33,7 +33,6 @@
     "sphinx.ext.autodoc",
     "sphinx.ext.intersphinx",
     "sphinx.ext.viewcode",
-    "sphinx_design",
     "sphinxext.rediraffe",
     "sphinxcontrib.mermaid",
     "sphinxext.opengraph",
```
`sphinx-build` command fails on missing `myst_parser._docs` module
```console
+ /usr/bin/sphinx-build -n -T -b man docs build/sphinx/man
Running Sphinx v5.0.1
making output directory... done

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/sphinx/cmd/build.py", line 272, in build_main
    app = Sphinx(args.sourcedir, args.confdir, args.outputdir,
  File "/usr/lib/python3.8/site-packages/sphinx/application.py", line 237, in __init__
    self.config.setup(self)
  File "/home/tkloczko/rpmbuild/BUILD/MyST-Parser-0.18.0/docs/conf.py", line 158, in setup
    from myst_parser._docs import (
ModuleNotFoundError: No module named 'myst_parser._docs'

Exception occurred:
  File "/home/tkloczko/rpmbuild/BUILD/MyST-Parser-0.18.0/docs/conf.py", line 158, in setup
    from myst_parser._docs import (
ModuleNotFoundError: No module named 'myst_parser._docs'
The full traceback has been saved in /tmp/sphinx-err-ho9lnx_7.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
```
And looks like indeed there is no sucj module in myst_parser/ dirextory.

### Reproduce the bug

Just run `phinx-build -n -T -b man docs build/sphinx/man` in project root directory.

### List your environment

List modules installed in build env
```console
Package                       Version
----------------------------- -----------------
alabaster                     0.7.12
appdirs                       1.4.4
attrs                         21.4.0
Babel                         2.10.1
beautifulsoup4                4.10.0
Brlapi                        0.8.3
build                         0.8.0
charset-normalizer            2.0.12
codespell                     2.1.0
cycler                        0.11.0
distro                        1.7.0
docutils                      0.17.1
extras                        1.0.0
fixtures                      4.0.0
flit_core                     3.7.1
fonttools                     4.33.3
gpg                           1.17.1-unknown
idna                          3.3
imagesize                     1.3.0
importlib-metadata            4.11.3
iniconfig                     1.1.1
Jinja2                        3.1.1
kiwisolver                    1.4.2
libcomps                      0.1.18
linkify-it-py                 2.0.0
lit                           14.0.4
louis                         3.21.0
lxml                          4.9.0
markdown-it-py                2.1.0
MarkupSafe                    2.1.1
matplotlib                    3.5.1
mdit-py-plugins               0.3.0
mdurl                         0.1.1
meson                         0.62.2
myst-parser                   0.17.2
numpy                         1.22.4
olefile                       0.46
packaging                     21.3
pbr                           5.8.1
pep517                        0.12.0
Pillow                        9.1.1
pip                           22.0.4
pluggy                        1.0.0
py                            1.11.0
Pygments                      2.12.0
PyGObject                     3.42.1
pyparsing                     3.0.9
pytest                        7.1.2
pytest-datadir                1.3.1
pytest_param_files            0.3.4
pytest-regressions            2.3.1
python-dateutil               2.8.2
pytz                          2022.1
PyYAML                        6.0
requests                      2.27.1
rpm                           4.17.0
scour                         0.38.2
six                           1.16.0
snowballstemmer               2.2.0
soupsieve                     2.3.2.post1
Sphinx                        5.0.1
sphinx-rtd-theme              1.0.0
sphinxcontrib-applehelp       1.0.2.dev20220410
sphinxcontrib-devhelp         1.0.2.dev20220410
sphinxcontrib-htmlhelp        2.0.0
sphinxcontrib-jsmath          1.0.1.dev20220410
sphinxcontrib-mermaid         0.7.1
sphinxcontrib-qthelp          1.0.3.dev20220410
sphinxcontrib-serializinghtml 1.1.5
sphinxext-opengraph           0.6.3
sphinxext-rediraffe           main
testtools                     2.5.0
tomli                         2.0.1
typing_extensions             4.2.0
uc-micro-py                   1.0.1
urllib3                       1.26.9
wheel                         0.37.1
zipp                          3.8.0
```

**Comment by kloczek** [comment]
Only commit related to documentation which I see is 391a8cd1.
I've been trying it anf sphinx still fails with sphinx 5.0.2.

<details>

```console
+ /usr/bin/sphinx-build -n -T -b man docs build/sphinx/man
Running Sphinx v5.0.2
making output directory... done
myst v0.18.0: MdParserConfig(commonmark_only=False, gfm_only=False, enable_extensions=['dollarmath', 'amsmath', 'deflist', 'fieldlist', 'html_admonition', 'html_image', 'colon_fence', 'smartquotes', 'replacements', 'linkify', 'strikethrough', 'substitution', 'tasklist'], disable_syntax=[], all_links_external=False, url_schemes=('http', 'https', 'mailto', 'ftp'), ref_domains=None, highlight_code_blocks=True, number_code_blocks=['typescript'], title_to_header=False, heading_anchors=2, heading_slug_func=None, footnote_transition=True, words_per_minute=200, sub_delimiters=('{', '}'), linkify_fuzzy_links=True, dmath_allow_labels=True, dmath_allow_space=True, dmath_allow_digits=True, dmath_double_inline=True, update_mathjax=True, mathjax_classes='tex2jax_process|mathjax_process|math|output_area')
loading intersphinx inventory from https://docs.python.org/3.7/objects.inv...
loading intersphinx inventory from https://www.sphinx-doc.org/en/master/objects.inv...
loading intersphinx inventory from https://markdown-it-py.readthedocs.io/en/latest/objects.inv...
building [mo]: targets for 0 po files that are out of date
building [man]: all manpages
updating environment: [new config] 18 added, 0 changed, 0 removed
reading sources... [100%] syntax/syntax
looking for now-outdated files... none found
pickling environment... done
checking consistency... done
writing... python-myst-parser.3 { intro syntax/syntax syntax/optional syntax/roles-and-directives configuration docutils faq/index develop/index develop/contributing develop/architecture develop/test_infrastructure develop/_changelog syntax/reference develop/background api/reference } failed

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/sphinx/cmd/build.py", line 276, in build_main
    app.build(args.force_all, filenames)
  File "/usr/lib/python3.8/site-packages/sphinx/application.py", line 329, in build
    self.builder.build_update()
  File "/usr/lib/python3.8/site-packages/sphinx/builders/__init__.py", line 285, in build_update
    self.build(['__all__'], to_build)
  File "/usr/lib/python3.8/site-packages/sphinx/builders/__init__.py", line 352, in build
    self.write(docnames, list(updated_docnames), method)
  File "/usr/lib/python3.8/site-packages/sphinx/util/__init__.py", line 517, in wrapper
    return f(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/sphinx/builders/manpage.py", line 98, in write
    docwriter.write(largetree, destination)
  File "/usr/lib/python3.8/site-packages/docutils/writers/__init__.py", line 78, in write
    self.translate()
  File "/usr/lib/python3.8/site-packages/sphinx/writers/manpage.py", line 29, in translate
    visitor = self.builder.create_translator(self.document, self.builder)
  File "/usr/lib/python3.8/site-packages/sphinx/builders/__init__.py", line 122, in create_translator
    return self.app.registry.create_translator(self, *args)
  File "/usr/lib/python3.8/site-packages/sphinx/registry.py", line 347, in create_translator
    setattr(translator, 'visit_' + name, MethodType(visit, translator))
TypeError: first argument must be callable

Exception occurred:
  File "/usr/lib/python3.8/site-packages/sphinx/registry.py", line 347, in create_translator
    setattr(translator, 'visit_' + name, MethodType(visit, translator))
TypeError: first argument must be callable
The full traceback has been saved in /tmp/sphinx-err-7hqzmkjd.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
```

```console
[tkloczko@devel-g2v SPECS]$ cat /tmp/sphinx-err-7hqzmkjd.log
# Sphinx version: 5.0.2
# Python version: 3.8.13 (CPython)
# Docutils version: 0.17.1 release
# Jinja2 version: 3.1.1
# Last messages:
#   develop/index
#   develop/contributing
#   develop/architecture
#   develop/test_infrastructure
#   develop/_changelog
#   syntax/reference
#   develop/background
#   api/reference
#   }
#   failed
# Loaded extensions:
#   sphinx.ext.mathjax (5.0.2) from /usr/lib/python3.8/site-packages/sphinx/ext/mathjax.py
#   sphinxcontrib.applehelp (1.0.2) from /usr/lib/python3.8/site-packages/sphinxcontrib/applehelp/__init__.py
#   sphinxcontrib.devhelp (1.0.2) from /usr/lib/python3.8/site-packages/sphinxcontrib/devhelp/__init__.py
#   sphinxcontrib.htmlhelp (2.0.0) from /usr/lib/python3.8/site-packages/sphinxcontrib/htmlhelp/__init__.py
#   sphinxcontrib.serializinghtml (1.1.5) from /usr/lib/python3.8/site-packages/sphinxcontrib/serializinghtml/__init__.py
#   sphinxcontrib.qthelp (1.0.3) from /usr/lib/python3.8/site-packages/sphinxcontrib/qthelp/__init__.py
#   alabaster (0.7.12) from /usr/lib/python3.8/site-packages/alabaster/__init__.py
#   myst_parser (0.18.0) from /home/tkloczko/rpmbuild/BUILD/MyST-Parser-0.18.0/myst_parser/__init__.py
#   sphinx.ext.autodoc.preserve_defaults (1.0) from /usr/lib/python3.8/site-packages/sphinx/ext/autodoc/preserve_defaults.py
#   sphinx.ext.autodoc.type_comment (5.0.2) from /usr/lib/python3.8/site-packages/sphinx/ext/autodoc/type_comment.py
#   sphinx.ext.autodoc (5.0.2) from /usr/lib/python3.8/site-packages/sphinx/ext/autodoc/__init__.py
#   sphinx.ext.intersphinx (5.0.2) from /usr/lib/python3.8/site-packages/sphinx/ext/intersphinx.py
#   sphinx.ext.viewcode (5.0.2) from /usr/lib/python3.8/site-packages/sphinx/ext/viewcode.py
#   sphinx_design (0.2.0) from /usr/lib/python3.8/site-packages/sphinx_design/__init__.py
#   sphinxext.rediraffe (unknown version) from /usr/lib/python3.8/site-packages/sphinxext/rediraffe.py
#   sphinxcontrib.mermaid (5.0.2) from /usr/lib/python3.8/site-packages/sphinxcontrib/mermaid.py
#   sphinxext.opengraph (unknown version) from /usr/lib/python3.8/site-packages/sphinxext/opengraph/__init__.py
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/sphinx/cmd/build.py", line 276, in build_main
    app.build(args.force_all, filenames)
  File "/usr/lib/python3.8/site-packages/sphinx/application.py", line 329, in build
    self.builder.build_update()
  File "/usr/lib/python3.8/site-packages/sphinx/builders/__init__.py", line 285, in build_update
    self.build(['__all__'], to_build)
  File "/usr/lib/python3.8/site-packages/sphinx/builders/__init__.py", line 352, in build
    self.write(docnames, list(updated_docnames), method)
  File "/usr/lib/python3.8/site-packages/sphinx/util/__init__.py", line 517, in wrapper
    return f(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/sphinx/builders/manpage.py", line 98, in write
    docwriter.write(largetree, destination)
  File "/usr/lib/python3.8/site-packages/docutils/writers/__init__.py", line 78, in write
    self.translate()
  File "/usr/lib/python3.8/site-packages/sphinx/writers/manpage.py", line 29, in translate
    visitor = self.builder.create_translator(self.document, self.builder)
  File "/usr/lib/python3.8/site-packages/sphinx/builders/__init__.py", line 122, in create_translator
    return self.app.registry.create_translator(self, *args)
  File "/usr/lib/python3.8/site-packages/sphinx/registry.py", line 347, in create_translator
    setattr(translator, 'visit_' + name, MethodType(visit, translator))
TypeError: first argument must be callable
```
</details>

BTW to be able use straight `sphinx-build` command it is necessary to appli patch like below
```patch
--- a/docs/conf.py
+++ b/docs/conf.py
@@ -3,6 +3,9 @@
 # This file only contains a selection of the most common options. For a full
 # list see the documentation:
 # https://www.sphinx-doc.org/en/master/usage/configuration.html
+import sys
+import os
+sys.path.append(os.path.abspath(".."))

 from datetime import date
```
That can of fix is suggested in sphinx example copy.py https://www.sphinx-doc.org/en/master/usage/configuration.html#example-of-configuration-file

**Comment by chrisjsewell** [comment]
> BTW to be able use straight sphinx-build command it is necessary to appli patch like below

I want be very clear here, adding to the system path is not the correct way to install Python packages, and I will be not be supporting it.
I have told you numerous times, over numerous packages how you need to install them to not get these errors, inline with https://github.com/executablebooks/MyST-Parser/blob/master/docs/develop/contributing.md

If you continue to open spurious bugs, because you have not followed these instructions, then I will have no recourse but to block you.

**Comment by chrisjsewell** [comment]
I want to help you, but you have to meet me half way here, because it feels like you just ignore what I tell you, every time you  open these issues

**Comment by kloczek** [comment]
> If you continue to open spurious bugs, because you have not followed these instructions, then I will have no recourse but to block you.

Please at least try to have look outside of python domain.
**Every** other project on that area produces documentation out of **source tree** .. not what is installed.
What you suggests causes:
- force use tox which venv assembly takes time and resources. Why I should do that if I'm already building package in isolated env in which are installed only precise build dependencies to build exact package?
- have installed in build env module which is just build (chicken and egg problem)
- causes risk that process of generating documentation will generate documentation different version than what you want.

Just rhetorical question: look on that from KISS principle point of view.
What is simpler? Three lines patch or adding another build dependencies and wait on tox?

I want only to point that less than 20% of all my packages with sphinx documentation (just checked and it is precisely 575 modules with sphinx documentation of 981 packages with python modules currently I have) only less than 12% needs that kind of fixe. Every other module with sphinx documentation is possible to generate without have module installed. Number of such modules recently is decreasing because most of the python maintainers simply didn't know that it is simpler way of generate documentation because they've copied some framework from other modules.

If you don't like that patch. That is perfectly fine. **Just ignore that**.
I'll keep it in my packages because it allows me to **standardise** documentation build process not only for your modules but across all packages with python modules with sphinx documentation.
I'm only INFORMING YOU that it is simpler way of doing something which does not break anything.
EOT.

**Comment by kloczek** [comment]
> I want to help you, but you have to meet me half way here, because it feels like you just ignore what I tell you, every time you open these issues

Here is `MyST-Parser` build env modules list.
If you want to use tox that is fine.
```console
Package                       Version
----------------------------- -----------------
alabaster                     0.7.12
attrs                         21.4.0
Babel                         2.10.2
beautifulsoup4                4.10.0
Brlapi                        0.8.3
build                         0.8.0
charset-normalizer            2.1.0
codespell                     2.1.0
cycler                        0.11.0
distro                        1.7.0
docutils                      0.17.1
extras                        1.0.0
fixtures                      4.0.0
flit_core                     3.7.1
fonttools                     4.33.3
gpg                           1.17.1-unknown
idna                          3.3
imagesize                     1.3.0
importlib-metadata            4.11.3
iniconfig                     1.1.1
Jinja2                        3.1.1
kiwisolver                    1.4.3
libcomps                      0.1.18
linkify-it-py                 2.0.0
louis                         3.22.0
markdown-it-py                2.1.0
MarkupSafe                    2.1.1
matplotlib                    3.5.2
mdit-py-plugins               0.3.0
mdurl                         0.1.1
numpy                         1.22.4
olefile                       0.46
packaging                     21.3
pbr                           5.8.1
pep517                        0.12.0
Pillow                        9.1.1
pip                           22.0.4
pluggy                        1.0.0
py                            1.11.0
Pygments                      2.12.0
PyGObject                     3.42.1
pyparsing                     3.0.9
pytest                        7.1.2
pytest-datadir                1.3.1
pytest_param_files            0.3.4
pytest-regressions            2.3.1
python-dateutil               2.8.2
pytz                          2022.1
PyYAML                        6.0
requests                      2.28.0
rpm                           4.17.0
six                           1.16.0
snowballstemmer               2.2.0
soupsieve                     2.3.2.post1
Sphinx                        5.0.2
sphinx_design                 0.2.0
sphinxcontrib-applehelp       1.0.2.dev20220410
sphinxcontrib-devhelp         1.0.2.dev20220410
sphinxcontrib-htmlhelp        2.0.0
sphinxcontrib-jsmath          1.0.1.dev20220410
sphinxcontrib-mermaid         0.7.1
sphinxcontrib-qthelp          1.0.3.dev20220410
sphinxcontrib-serializinghtml 1.1.5
sphinxext-opengraph           0.6.3
sphinxext-rediraffe           main
testtools                     2.5.0
tomli                         2.0.1
typing_extensions             4.2.0
uc-micro-py                   1.0.1
urllib3                       1.26.9
wheel                         0.37.1
zipp                          3.8.0
```

**Comment by kloczek** [comment]
> I want to help you, but you have to meet me half way here, because it feels like you just ignore what I tell you, every time you open these issues

Will try to remember about to not to mention that however please understand that I'm already maintaining +980 packages build procedures so on reporting some issue I'm following relatively simple check list procedure which has one point to report or at least ask to commit some patch which I'm using  which I think that it could have some value outside strict packaging build procedures.
On such scale it is really hard to remember everything.
I can only apologise if it will happen again 😞

**Comment by chrisjsewell** [comment]
> I can only apologise if it will happen again 😞

No that's, fine, it's not the end of the world, but I feel I needed to say something, otherwise nothing would change.

Have you considered opening some kind of PEP(s) (https://peps.python.org/pep-0000/) for standardisation of testing/documentation.

> Every other project on that area produces documentation out of source tree .. not what is installed.

If packages could be "installed", by simply adding them to the system path, why is this not the standard way to install a package?

Lets take myst-nb as an example, it has a bunch of entry points it needs to install: https://github.com/executablebooks/MyST-NB/blob/9099e2ccc65490ce5329a9dc6d837b7811ed996c/pyproject.toml#L57-L68
this does not happen if you just add it to the system path.
Adding to the system path also does not take care of resolving dependency version constraints

> Just rhetorical question: look on that from KISS principle point of view.

Literally every issue you open, is because your system path additions do not take into account the correct versions of packages and you end up with incorrect versions of everything

> Please at least try to have look outside of python domain.

what other language/framework simply adds thing to a system path to install them?

I work across numerous languages, I can tell you there are none

**Comment by kloczek** [comment]
> Literally every issue you open, is because your system path additions do not take into account the correct versions of packages and you end up with incorrect versions of everything

Hmm this implies that docs/ content should not be used to generate documentation of current version.

Nevertheless please try to focus on the issue which is still unresolved,
You have list of modules with versions in which documentation build fails.
Could you please at least try to reproduce what I've reported?

**Comment by chrisjsewell** [comment]
> Could you please at least try to reproduce what I've reported?

>  `File "/home/tkloczko/rpmbuild/BUILD/MyST-Parser-0.18.0/docs/conf.py", line 158, in setup`
> List modules installed in build env:
> `myst-parser                   0.17.2`

You're trying to build the v0.18.0 documentation with v0.17.2 of the package 🤷 

I don't need to reproduce something that will clearly fail, neither do I have the bandwidth to do so

I've nothing more to say on this; again if you persist on opening this false bugs, I will block you

**Comment by kloczek** [comment]
> You're trying to build the v0.18.0 documentation with v0.17.2 of the package 🤷
> 
> I don't need to reproduce something that will clearly fail, neither do I have the bandwidth to do so
> 
> I've nothing more to say on this; again if you persist on opening this false bugs, I will block you

Issue is that is not true.
Please look one more time on attached sphinx-build call trace https://github.com/executablebooks/MyST-Parser/issues/582#issuecomment-1162841135.
Please look on `<<< HERE`
```console
# Loaded extensions:
#   sphinx.ext.mathjax (5.0.2) from /usr/lib/python3.8/site-packages/sphinx/ext/mathjax.py
#   sphinxcontrib.applehelp (1.0.2) from /usr/lib/python3.8/site-packages/sphinxcontrib/applehelp/__init__.py
#   sphinxcontrib.devhelp (1.0.2) from /usr/lib/python3.8/site-packages/sphinxcontrib/devhelp/__init__.py
#   sphinxcontrib.htmlhelp (2.0.0) from /usr/lib/python3.8/site-packages/sphinxcontrib/htmlhelp/__init__.py
#   sphinxcontrib.serializinghtml (1.1.5) from /usr/lib/python3.8/site-packages/sphinxcontrib/serializinghtml/__init__.py
#   sphinxcontrib.qthelp (1.0.3) from /usr/lib/python3.8/site-packages/sphinxcontrib/qthelp/__init__.py
#   alabaster (0.7.12) from /usr/lib/python3.8/site-packages/alabaster/__init__.py
#   myst_parser (0.18.0) from /home/tkloczko/rpmbuild/BUILD/MyST-Parser-0.18.0/myst_parser/__init__.py    <<< HERE
#   sphinx.ext.autodoc.preserve_defaults (1.0) from /usr/lib/python3.8/site-packages/sphinx/ext/autodoc/preserve_defaults.py
#   sphinx.ext.autodoc.type_comment (5.0.2) from /usr/lib/python3.8/site-packages/sphinx/ext/autodoc/type_comment.py
#   sphinx.ext.autodoc (5.0.2) from /usr/lib/python3.8/site-packages/sphinx/ext/autodoc/__init__.py
#   sphinx.ext.intersphinx (5.0.2) from /usr/lib/python3.8/site-packages/sphinx/ext/intersphinx.py
#   sphinx.ext.viewcode (5.0.2) from /usr/lib/python3.8/site-packages/sphinx/ext/viewcode.py
#   sphinx_design (0.2.0) from /usr/lib/python3.8/site-packages/sphinx_design/__init__.py
#   sphinxext.rediraffe (unknown version) from /usr/lib/python3.8/site-packages/sphinxext/rediraffe.py
#   sphinxcontrib.mermaid (5.0.2) from /usr/lib/python3.8/site-packages/sphinxcontrib/mermaid.py
#   sphinxext.opengraph (unknown version) from /usr/lib/python3.8/site-packages/sphinxext/opengraph/__init__.py
````

**Comment by kloczek** [comment]
Ping .. 
Issue still is unresolved because there is no `'myst_parser._docs'` in https://github.com/executablebooks/MyST-Parser tree.

**Comment by kloczek** [comment]
```console
[tkloczko@devel-g2v MyST-Parser-0.18.0]$ grep _docs docs/conf.py
    "path_to_docs": "docs",
    from myst_parser._docs import (
```

**Comment by chrisjsewell** [comment]
> Issue still is unresolved because there is no 'myst_parser._docs' in [executablebooks/MyST-Parser](https://github.com/executablebooks/MyST-Parser) tree.

There absolutely is: download the source from https://pypi.org/project/myst-parser/#files, and you can clearly see the `_docs.py` file

**Comment by kloczek** [comment]
So what is the problem to add that to git tree?

**Comment by chrisjsewell** [comment]
> So what is the problem to add that to git tree?

Well it is in the git tree, otherwise it literally would not be in the source distribution
