### ISSUE TITLE
0.17.2: `nbclassic` documentation build fails in `myst-parser` code

### ISSUE THREAD

**Issue by kloczek** [executablebooks/MyST-Parser#593]
### Describe the bug

**context**
On building `nbclassic` documentation build fails in `myst-parser`.

**expectation**
It should be no fails

**bug**
sphinx fails in `myst-parser` code with call trace.

```console
[tkloczko@devel-g2v nbclassic-0.4.0]$ /usr/bin/sphinx-build -n -T -b man docs/source build/sphinx/man
Running Sphinx v5.0.2
DEBUG:: sys.path
================
/usr/bin
/usr/lib64/python38.zip
/usr/lib64/python3.8
/usr/lib64/python3.8/lib-dynload
/usr/lib64/python3.8/site-packages
/usr/lib/python3.8/site-packages
repo_root
=====================
/home/tkloczko/rpmbuild/BUILD/nbclassic-0.4.0
DEBUG:: Post insert to sys.path
===============================
/home/tkloczko/rpmbuild/BUILD/nbclassic-0.4.0
/usr/bin
/usr/lib64/python38.zip
/usr/lib64/python3.8
/usr/lib64/python3.8/lib-dynload
/usr/lib64/python3.8/site-packages
/usr/lib/python3.8/site-packages
WARNING: Invalid configuration value found: 'language = None'. Update your configuration to a valid langauge code. Falling back to 'en' (English).
Initializing GitHub plugin
loading intersphinx inventory from https://ipython.readthedocs.io/en/stable/objects.inv...
loading intersphinx inventory from https://nbconvert.readthedocs.io/en/latest/objects.inv...
loading intersphinx inventory from https://nbformat.readthedocs.io/en/latest/objects.inv...
loading intersphinx inventory from https://jupyter.readthedocs.io/en/latest/objects.inv...
intersphinx inventory has moved: https://jupyter.readthedocs.io/en/latest/objects.inv -> https://docs.jupyter.org/en/latest/objects.inv
[autosummary] generating autosummary for: changelog.md, comms.rst, config_overview.rst, contributing.rst, development_faq.rst, examples/Notebook/Connecting with the Qt Console.ipynb, examples/Notebook/Custom Keyboard Shortcuts.ipynb, examples/Notebook/Distributing Jupyter Extensions as Python Packages.ipynb, examples/Notebook/Importing Notebooks.ipynb, examples/Notebook/JavaScript Notebook Extensions.ipynb, ..., extending/index.rst, extending/keymaps.rst, extending/savehooks.rst, frontend_config.rst, index.rst, notebook.rst, public_server.rst, security.rst, troubleshooting.rst, ui_components.rst
myst v0.17.2: MdParserConfig(commonmark_only=False, gfm_only=False, enable_extensions=['html_image'], linkify_fuzzy_links=True, dmath_allow_labels=True, dmath_allow_space=True, dmath_allow_digits=True, dmath_double_inline=False, update_mathjax=False, mathjax_classes='tex2jax_process|mathjax_process|math|output_area', disable_syntax=[], all_links_external=False, url_schemes=('http', 'https', 'mailto', 'ftp'), ref_domains=None, highlight_code_blocks=True, number_code_blocks=[], title_to_header=False, heading_anchors=None, heading_slug_func=None, footnote_transition=True, sub_delimiters=('{', '}'), words_per_minute=200)
building [mo]: targets for 0 po files that are out of date
building [man]: all manpages
updating environment: [new config] 32 added, 0 changed, 0 removed
reading sources... [100%] ui_components
CONTRIBUTING.rst:46: WARNING: Title underline too short.

Installing the Jupyter NbClassic
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
CONTRIBUTING.rst:46: WARNING: Title underline too short.

Installing the Jupyter NbClassic
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
/home/tkloczko/rpmbuild/BUILD/nbclassic-0.4.0/docs/source/index.rst:19: WARNING: toctree contains reference to nonexisting document 'config'
looking for now-outdated files... none found
pickling environment... done
checking consistency... done
writing... jupyternotebook.1 { notebook ui_components examples/Notebook/examples_index examples/Notebook/What is the Jupyter Notebook examples/Notebook/Notebook Basics examples/Notebook/Running Code examples/Notebook/Working With Markdown Cells examples/Notebook/Custom Keyboard Shortcuts examples/Notebook/JavaScript Notebook Extensions examples/Notebook/Importing Notebooks examples/Notebook/Connecting with the Qt Console examples/Notebook/Typesetting Equations troubleshooting changelog comms config_overview frontend_config public_server security examples/Notebook/Distributing Jupyter Extensions as Python Packages extending/index extending/contents extending/savehooks extending/handlers extending/frontend_extensions extending/keymaps extending/bundler_extensions contributing development_faq examples/Notebook/nbpackage/mynotebook examples/Notebook/nbpackage/nbs/other } /home/tkloczko/rpmbuild/BUILD/nbclassic-0.4.0/docs/source/public_server.rst:50: WARNING: py:attr reference target not found: NotebookApp.password
/home/tkloczko/rpmbuild/BUILD/nbclassic-0.4.0/docs/source/public_server.rst:113: WARNING: py:func reference target not found: notebook.auth.security.passwd
/home/tkloczko/rpmbuild/BUILD/nbclassic-0.4.0/docs/source/public_server.rst:126: WARNING: py:func reference target not found: notebook.auth.security.passwd
/home/tkloczko/rpmbuild/BUILD/nbclassic-0.4.0/docs/source/extending/contents.rst:11: WARNING: py:class reference target not found: manager.ContentsManager
/home/tkloczko/rpmbuild/BUILD/nbclassic-0.4.0/docs/source/extending/contents.rst:11: WARNING: py:class reference target not found: filemanager.FileContentsManager
/home/tkloczko/rpmbuild/BUILD/nbclassic-0.4.0/docs/source/extending/contents.rst:75: WARNING: py:class reference target not found: nbformat.notebooknode.NotebookNode
/home/tkloczko/rpmbuild/BUILD/nbclassic-0.4.0/docs/source/extending/contents.rst:186: WARNING: py:class reference target not found: manager.ContentsManager
/home/tkloczko/rpmbuild/BUILD/nbclassic-0.4.0/docs/source/extending/contents.rst:198:<autosummary>:1: WARNING: py:obj reference target not found: notebook.services.contents.manager.ContentsManager.get
/home/tkloczko/rpmbuild/BUILD/nbclassic-0.4.0/docs/source/extending/contents.rst:198:<autosummary>:1: WARNING: py:obj reference target not found: notebook.services.contents.manager.ContentsManager.save
/home/tkloczko/rpmbuild/BUILD/nbclassic-0.4.0/docs/source/extending/contents.rst:198:<autosummary>:1: WARNING: py:obj reference target not found: notebook.services.contents.manager.ContentsManager.delete_file
/home/tkloczko/rpmbuild/BUILD/nbclassic-0.4.0/docs/source/extending/contents.rst:198:<autosummary>:1: WARNING: py:obj reference target not found: notebook.services.contents.manager.ContentsManager.rename_file
/home/tkloczko/rpmbuild/BUILD/nbclassic-0.4.0/docs/source/extending/contents.rst:198:<autosummary>:1: WARNING: py:obj reference target not found: notebook.services.contents.manager.ContentsManager.file_exists
/home/tkloczko/rpmbuild/BUILD/nbclassic-0.4.0/docs/source/extending/contents.rst:198:<autosummary>:1: WARNING: py:obj reference target not found: notebook.services.contents.manager.ContentsManager.dir_exists
/home/tkloczko/rpmbuild/BUILD/nbclassic-0.4.0/docs/source/extending/contents.rst:198:<autosummary>:1: WARNING: py:obj reference target not found: notebook.services.contents.manager.ContentsManager.is_hidden
/home/tkloczko/rpmbuild/BUILD/nbclassic-0.4.0/docs/source/extending/contents.rst:211: WARNING: py:meth reference target not found: manager.ContentsManager.save
/home/tkloczko/rpmbuild/BUILD/nbclassic-0.4.0/docs/source/extending/contents.rst:216: WARNING: py:meth reference target not found: manager.ContentsManager.save
/home/tkloczko/rpmbuild/BUILD/nbclassic-0.4.0/docs/source/extending/contents.rst:229: WARNING: py:mod reference target not found: notebook.services.contents.checkpoints
/home/tkloczko/rpmbuild/BUILD/nbclassic-0.4.0/docs/source/extending/contents.rst:242:<autosummary>:1: WARNING: py:obj reference target not found: notebook.services.contents.checkpoints.Checkpoints.rename_checkpoint
/home/tkloczko/rpmbuild/BUILD/nbclassic-0.4.0/docs/source/extending/contents.rst:242:<autosummary>:1: WARNING: py:obj reference target not found: notebook.services.contents.checkpoints.Checkpoints.list_checkpoints
/home/tkloczko/rpmbuild/BUILD/nbclassic-0.4.0/docs/source/extending/contents.rst:242:<autosummary>:1: WARNING: py:obj reference target not found: notebook.services.contents.checkpoints.Checkpoints.delete_checkpoint
/home/tkloczko/rpmbuild/BUILD/nbclassic-0.4.0/docs/source/extending/contents.rst:242:<autosummary>:1: WARNING: py:obj reference target not found: notebook.services.contents.checkpoints.GenericCheckpointsMixin.create_file_checkpoint
/home/tkloczko/rpmbuild/BUILD/nbclassic-0.4.0/docs/source/extending/contents.rst:242:<autosummary>:1: WARNING: py:obj reference target not found: notebook.services.contents.checkpoints.GenericCheckpointsMixin.create_notebook_checkpoint
/home/tkloczko/rpmbuild/BUILD/nbclassic-0.4.0/docs/source/extending/contents.rst:242:<autosummary>:1: WARNING: py:obj reference target not found: notebook.services.contents.checkpoints.GenericCheckpointsMixin.get_file_checkpoint
/home/tkloczko/rpmbuild/BUILD/nbclassic-0.4.0/docs/source/extending/contents.rst:242:<autosummary>:1: WARNING: py:obj reference target not found: notebook.services.contents.checkpoints.GenericCheckpointsMixin.get_notebook_checkpoint
/home/tkloczko/rpmbuild/BUILD/nbclassic-0.4.0/docs/source/extending/contents.rst:272: WARNING: py:mod reference target not found: notebook.services.contents.filecheckpoints
/home/tkloczko/rpmbuild/BUILD/nbclassic-0.4.0/docs/source/extending/contents.rst:279: WARNING: py:mod reference target not found: notebook.services.contents.tests
/home/tkloczko/rpmbuild/BUILD/nbclassic-0.4.0/docs/source/examples/Notebook/Running Code.ipynb:: WARNING: unknown node type: <CodeAreaNode: <literal_block...>>
failed

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/sphinx/cmd/build.py", line 276, in build_main
    app.build(args.force_all, filenames)
  File "/usr/lib/python3.8/site-packages/sphinx/application.py", line 329, in build
    self.builder.build_update()
  File "/usr/lib/python3.8/site-packages/sphinx/builders/__init__.py", line 285, in build_update
    self.build(['__all__'], to_build)
  File "/usr/lib/python3.8/site-packages/sphinx/builders/__init__.py", line 352, in build
    self.write(docnames, list(updated_docnames), method)
  File "/usr/lib/python3.8/site-packages/sphinx/util/__init__.py", line 517, in wrapper
    return f(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/sphinx/builders/manpage.py", line 98, in write
    docwriter.write(largetree, destination)
  File "/usr/lib/python3.8/site-packages/docutils/writers/__init__.py", line 78, in write
    self.translate()
  File "/usr/lib/python3.8/site-packages/sphinx/writers/manpage.py", line 31, in translate
    self.document.walkabout(visitor)
  File "/usr/lib/python3.8/site-packages/docutils/nodes.py", line 227, in walkabout
    if child.walkabout(visitor):
  File "/usr/lib/python3.8/site-packages/docutils/nodes.py", line 227, in walkabout
    if child.walkabout(visitor):
  File "/usr/lib/python3.8/site-packages/docutils/nodes.py", line 227, in walkabout
    if child.walkabout(visitor):
  [Previous line repeated 7 more times]
  File "/usr/lib/python3.8/site-packages/docutils/nodes.py", line 240, in walkabout
    visitor.dispatch_departure(self)
  File "/usr/lib/python3.8/site-packages/sphinx/util/docutils.py", line 546, in dispatch_departure
    super().dispatch_departure(node)
  File "/usr/lib/python3.8/site-packages/docutils/nodes.py", line 2034, in dispatch_departure
    return method(node)
  File "/usr/lib/python3.8/site-packages/docutils/nodes.py", line 2056, in unknown_departure
    raise NotImplementedError(
NotImplementedError: <class 'sphinx.writers.manpage.ManualPageTranslator'> departing unknown node type: CodeAreaNode

Exception occurred:
  File "/usr/lib/python3.8/site-packages/docutils/nodes.py", line 2056, in unknown_departure
    raise NotImplementedError(
NotImplementedError: <class 'sphinx.writers.manpage.ManualPageTranslator'> departing unknown node type: CodeAreaNode
The full traceback has been saved in /tmp/sphinx-err-19h8i41j.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
```
```console
[tkloczko@devel-g2v nbclassic-0.4.0]$ cat /tmp/sphinx-err-19h8i41j.log
# Sphinx version: 5.0.2
# Python version: 3.8.13 (CPython)
# Docutils version: 0.17.1 release
# Jinja2 version: 3.1.1
# Last messages:
#   extending/handlers
#   extending/frontend_extensions
#   extending/keymaps
#   extending/bundler_extensions
#   contributing
#   development_faq
#   examples/Notebook/nbpackage/mynotebook
#   examples/Notebook/nbpackage/nbs/other
#   }
#   failed
# Loaded extensions:
#   sphinx.ext.mathjax (5.0.2) from /usr/lib/python3.8/site-packages/sphinx/ext/mathjax.py
#   sphinxcontrib.applehelp (1.0.2) from /usr/lib/python3.8/site-packages/sphinxcontrib/applehelp/__init__.py
#   sphinxcontrib.devhelp (1.0.2) from /usr/lib/python3.8/site-packages/sphinxcontrib/devhelp/__init__.py
#   sphinxcontrib.htmlhelp (2.0.0) from /usr/lib/python3.8/site-packages/sphinxcontrib/htmlhelp/__init__.py
#   sphinxcontrib.serializinghtml (1.1.5) from /usr/lib/python3.8/site-packages/sphinxcontrib/serializinghtml/__init__.py
#   sphinxcontrib.qthelp (1.0.3) from /usr/lib/python3.8/site-packages/sphinxcontrib/qthelp/__init__.py
#   alabaster (0.7.12) from /usr/lib/python3.8/site-packages/alabaster/__init__.py
#   sphinx.ext.autodoc.preserve_defaults (1.0) from /usr/lib/python3.8/site-packages/sphinx/ext/autodoc/preserve_defaults.py
#   sphinx.ext.autodoc.type_comment (5.0.2) from /usr/lib/python3.8/site-packages/sphinx/ext/autodoc/type_comment.py
#   sphinx.ext.autodoc (5.0.2) from /usr/lib/python3.8/site-packages/sphinx/ext/autodoc/__init__.py
#   sphinx.ext.doctest (5.0.2) from /usr/lib/python3.8/site-packages/sphinx/ext/doctest.py
#   sphinx.ext.intersphinx (5.0.2) from /usr/lib/python3.8/site-packages/sphinx/ext/intersphinx.py
#   sphinx.ext.autosummary (5.0.2) from /usr/lib/python3.8/site-packages/sphinx/ext/autosummary/__init__.py
#   IPython.sphinxext.ipython_console_highlighting (unknown version) from /usr/lib/python3.8/site-packages/IPython/sphinxext/ipython_console_highlighting.py
#   nbsphinx (0.8.8) from /usr/lib/python3.8/site-packages/nbsphinx.py
#   sphinxcontrib_github_alt (unknown version) from /usr/lib/python3.8/site-packages/sphinxcontrib_github_alt.py
#   myst_parser (0.17.2) from /usr/lib/python3.8/site-packages/myst_parser/__init__.py
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/sphinx/cmd/build.py", line 276, in build_main
    app.build(args.force_all, filenames)
  File "/usr/lib/python3.8/site-packages/sphinx/application.py", line 329, in build
    self.builder.build_update()
  File "/usr/lib/python3.8/site-packages/sphinx/builders/__init__.py", line 285, in build_update
    self.build(['__all__'], to_build)
  File "/usr/lib/python3.8/site-packages/sphinx/builders/__init__.py", line 352, in build
    self.write(docnames, list(updated_docnames), method)
  File "/usr/lib/python3.8/site-packages/sphinx/util/__init__.py", line 517, in wrapper
    return f(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/sphinx/builders/manpage.py", line 98, in write
    docwriter.write(largetree, destination)
  File "/usr/lib/python3.8/site-packages/docutils/writers/__init__.py", line 78, in write
    self.translate()
  File "/usr/lib/python3.8/site-packages/sphinx/writers/manpage.py", line 31, in translate
    self.document.walkabout(visitor)
  File "/usr/lib/python3.8/site-packages/docutils/nodes.py", line 227, in walkabout
    if child.walkabout(visitor):
  File "/usr/lib/python3.8/site-packages/docutils/nodes.py", line 227, in walkabout
    if child.walkabout(visitor):
  File "/usr/lib/python3.8/site-packages/docutils/nodes.py", line 227, in walkabout
    if child.walkabout(visitor):
  [Previous line repeated 7 more times]
  File "/usr/lib/python3.8/site-packages/docutils/nodes.py", line 240, in walkabout
    visitor.dispatch_departure(self)
  File "/usr/lib/python3.8/site-packages/sphinx/util/docutils.py", line 546, in dispatch_departure
    super().dispatch_departure(node)
  File "/usr/lib/python3.8/site-packages/docutils/nodes.py", line 2034, in dispatch_departure
    return method(node)
  File "/usr/lib/python3.8/site-packages/docutils/nodes.py", line 2056, in unknown_departure
    raise NotImplementedError(
NotImplementedError: <class 'sphinx.writers.manpage.ManualPageTranslator'> departing unknown node type: CodeAreaNode
```

### Reproduce the bug

git clone https://github.com/jupyterlab/nbclassic/
cd nbclassic
sphinx-build -n -T -b man docs/source build/sphinx/man

### List your environment

```console
Package                       Version
----------------------------- -----------------
alabaster                     0.7.12
anyio                         3.6.1
argon2-cffi                   21.1.0
asttokens                     2.0.5
attrs                         22.1.0.dev0
Babel                         2.10.2
backcall                      0.2.0
beautifulsoup4                4.10.0
bleach                        5.0.0
Brlapi                        0.8.3
build                         0.8.0
cffi                          1.15.0
charset-normalizer            2.1.0
codespell                     2.1.0
cycler                        0.11.0
debugpy                       1.6.0
decorator                     5.1.1
defusedxml                    0.7.1
deprecation                   2.1.0
distro                        1.7.0
docutils                      0.17.1
entrypoints                   0.4
executing                     0.8.3
extras                        1.0.0
fastjsonschema                2.15.3
fixtures                      4.0.0
fonttools                     4.33.3
gpg                           1.17.1-unknown
html5lib                      1.1
idna                          3.3
imagesize                     1.3.0
importlib-metadata            4.12.0
importlib-resources           5.8.0
iniconfig                     1.1.1
ipykernel                     6.15.0
ipython                       8.4.0
ipython-genutils              0.2.0
jedi                          0.18.1
Jinja2                        3.1.1
jsonschema                    4.6.1
jupyter-client                7.3.4
jupyter-core                  4.10.0
jupyter-packaging             0.12.2
jupyter-server                1.18.0
jupyterlab-pygments           0.1.2
kiwisolver                    1.4.3
libcomps                      0.1.18
louis                         3.22.0
markdown-it-py                2.1.0
MarkupSafe                    2.1.1
matplotlib                    3.5.2
matplotlib-inline             0.1.3
mdit-py-plugins               0.3.0
mdurl                         0.1.1
mistune                       2.0.2
myst-parser                   0.17.2
nbclient                      0.6.6
nbconvert                     6.5.0
nbformat                      5.4.0
nbsphinx                      0.8.8
nest-asyncio                  1.5.5
notebook                      6.4.12
notebook-shim                 0.1.0
numpy                         1.23.0
olefile                       0.46
packaging                     21.3
pandocfilters                 1.5.0
parso                         0.8.3
pbr                           5.8.1
pep517                        0.12.0
pexpect                       4.8.0
pickleshare                   0.7.5
Pillow                        9.1.1
pip                           22.0.4
pluggy                        1.0.0
ply                           3.11
prometheus-client             0.14.1
prompt-toolkit                3.0.29
psutil                        5.9.0
ptyprocess                    0.7.0
pure-eval                     0.2.2
py                            1.11.0
pycparser                     2.21
Pygments                      2.12.0
PyGObject                     3.42.1
pyparsing                     3.0.9
pyrsistent                    0.18.1
pytest                        7.1.2
pytest-tornasync              0.6.0.post2
python-dateutil               2.8.2
pytz                          2022.1
PyYAML                        6.0
pyzmq                         23.2.0
requests                      2.28.1
rpm                           4.17.0
Send2Trash                    1.8.0
setuptools                    62.6.0
six                           1.16.0
sniffio                       1.2.0
snowballstemmer               2.2.0
soupsieve                     2.3.2.post1
Sphinx                        5.0.2
sphinxcontrib-applehelp       1.0.2.dev20220410
sphinxcontrib-devhelp         1.0.2.dev20220410
sphinxcontrib_github_alt      1.2
sphinxcontrib-htmlhelp        2.0.0
sphinxcontrib-jsmath          1.0.1.dev20220410
sphinxcontrib-qthelp          1.0.3.dev20220410
sphinxcontrib-serializinghtml 1.1.5
stack-data                    0.3.0
terminado                     0.13.3
testtools                     2.5.0
tinycss2                      1.1.1
tomli                         2.0.1
tomlkit                       0.11.0
tornado                       6.1
traitlets                     5.3.0
typing_extensions             4.2.0
urllib3                       1.26.9
wcwidth                       0.2.5
webencodings                  0.5.1
websocket-client              1.3.2
wheel                         0.37.1
zipp                          3.8.0
```

**Comment by chrisjsewell** [comment]
`CodeAreaNode` is not a node that myst-parser registers, I suggest it may be from `nbsphinx` and you should raise it there
