### ISSUE TITLE
[Docs] Python API Docs out of date re: module structure

### ISSUE THREAD

**Issue by sneakers-the-rat** [executablebooks/MyST-Parser#597]
### Describe the bug

**context**
When I browse the [API docs](https://myst-parser.readthedocs.io/en/latest/api/reference.html), they tell me that I should use `myst_parser.docutils_.Parser` to parse a document

**expectation**
I expected to be able to import `myst_parser.docutils_.Parser`

**bug**
But instead an `ImportError` happens:

```python
Traceback (most recent call last):
  File "./.pyenv/versions/3.9.1/lib/python3.9/code.py", line 90, in runcode
    exec(code, self.locals)
  File "<input>", line 5, in <module>
AttributeError: module 'myst_parser' has no attribute 'docutils_'
```

**suggestion**

I just had to use 

```python
from myst_parser.parsers.docutils_ import Parser
```

instead!

### Reproduce the bug

```python
from myst_parser.docutils_ import Parser
```

### List your environment

`myst_parser.__version__ == 0.18.0`

**Comment by chrisjsewell** [comment]
Heya, I can't reproduce this issue, and myst-parser 0.18.0 does have a module `myst_parser.docutils_` : https://github.com/executablebooks/MyST-Parser/blob/v0.18.0/myst_parser/docutils_.py, from which you can import `Parser`

Can you perhaps provide more detail, about your system and how you installed it, and whether the file is actually present
