### ISSUE TITLE
Regression since 0.18.0 translated messages starting with `---` are parsed as YAML front matter

### ISSUE THREAD

**Issue by n-peugnet** [executablebooks/MyST-Parser#657]
### Describe the bug

**context**
In a Sphinx project translated in another language. When compiling the docs for the secondary language, if one of the translated message start with 3 dashes `---`, then it is interpreted by MyST-Parser as an YAML front matter.

For instance with an `index.md` like this:

```markdown
# Hello world!

--- hello
```

And a messages catalog in `locales/fr/LC_MESSAGES/index.po` like this:
```po
#: ../../source/index.md:3
msgid "--- hello"
msgstr "--- coucou"
```

**expectation**
MyST should not try to parse any translated messages into an YAML front matter. And it should be possible to have a paragraph starting with three dashes. MyST-Parser prior to version 0.18.0 gave the expected result.

**bug**
But instead here's an error message I ran into

```
Traceback (most recent call last):
  File "/tmp/test/.venv/lib/python3.10/site-packages/sphinx/cmd/build.py", line 276, in build_main
    app.build(args.force_all, filenames)
  File "/tmp/test/.venv/lib/python3.10/site-packages/sphinx/application.py", line 330, in build
    self.builder.build_update()
  File "/tmp/test/.venv/lib/python3.10/site-packages/sphinx/builders/__init__.py", line 286, in build_update
    self.build(to_build,
  File "/tmp/test/.venv/lib/python3.10/site-packages/sphinx/builders/__init__.py", line 300, in build
    updated_docnames = set(self.read())
  File "/tmp/test/.venv/lib/python3.10/site-packages/sphinx/builders/__init__.py", line 407, in read
    self._read_serial(docnames)
  File "/tmp/test/.venv/lib/python3.10/site-packages/sphinx/builders/__init__.py", line 428, in _read_serial
    self.read_doc(docname)
  File "/tmp/test/.venv/lib/python3.10/site-packages/sphinx/builders/__init__.py", line 468, in read_doc
    doctree = read_doc(self.app, self.env, self.env.doc2path(docname))
  File "/tmp/test/.venv/lib/python3.10/site-packages/sphinx/io.py", line 181, in read_doc
    pub.publish()
  File "/tmp/test/.venv/lib/python3.10/site-packages/docutils/core.py", line 219, in publish
    self.apply_transforms()
  File "/tmp/test/.venv/lib/python3.10/site-packages/docutils/core.py", line 200, in apply_transforms
    self.document.transformer.apply_transforms()
  File "/tmp/test/.venv/lib/python3.10/site-packages/sphinx/transforms/__init__.py", line 79, in apply_transforms
    super().apply_transforms()
  File "/tmp/test/.venv/lib/python3.10/site-packages/docutils/transforms/__init__.py", line 171, in apply_transforms
    transform.apply(**kwargs)
  File "/tmp/test/.venv/lib/python3.10/site-packages/sphinx/transforms/i18n.py", line 149, in apply
    patch = publish_msgstr(self.app, msgstr, source,
  File "/tmp/test/.venv/lib/python3.10/site-packages/sphinx/transforms/i18n.py", line 63, in publish_msgstr
    doc = reader.read(
  File "/tmp/test/.venv/lib/python3.10/site-packages/docutils/readers/__init__.py", line 72, in read
    self.parse()
  File "/tmp/test/.venv/lib/python3.10/site-packages/docutils/readers/__init__.py", line 78, in parse
    self.parser.parse(self.input, document)
  File "/tmp/test/.venv/lib/python3.10/site-packages/myst_parser/parsers/sphinx_.py", line 57, in parse
    topmatter = read_topmatter(inputstring)
  File "/tmp/test/.venv/lib/python3.10/site-packages/myst_parser/config/main.py", line 404, in read_topmatter
    assert isinstance(metadata, dict)
AssertionError

Exception occurred:
  File "/tmp/test/.venv/lib/python3.10/site-packages/myst_parser/config/main.py", line 404, in read_topmatter
    assert isinstance(metadata, dict)
AssertionError

```

The bug only happens if the message is indeed translated. And compiling for the primary language do not make it happen either.
This is quite a problem as is prevents me from upgrading to MyST-Parser 0.18+, thus to Sphinx 5+ too.

### Reproduce the bug

Here is a reproducer

```
virtualenv .venv
. .venv/bin/activate
pip install sphinx==4.5.0 myst-parser
sphinx-quickstart --sep -p test -a test -v test -r test -l en --extensions myst_parser
rm source/index.rst
echo '# Hello world!

--- hello
' > source/index.md
mkdir -p source/locales/fr/LC_MESSAGES
echo '#: ../../source/index.md:3
msgid "--- hello"
msgstr "--- coucou"
' > source/locales/fr/LC_MESSAGES/index.po
make html O='-Dlanguage=fr -v'
```

### List your environment

```console
$ pip list
Package                       Version
----------------------------- ---------
alabaster                     0.7.12
Babel                         2.11.0
certifi                       2022.12.7
charset-normalizer            2.1.1
docutils                      0.17.1
idna                          3.4
imagesize                     1.4.1
Jinja2                        3.1.2
markdown-it-py                2.1.0
MarkupSafe                    2.1.1
mdit-py-plugins               0.3.3
mdurl                         0.1.2
myst-parser                   0.18.1
packaging                     22.0
pip                           22.3
Pygments                      2.13.0
pytz                          2022.6
PyYAML                        6.0
requests                      2.28.1
setuptools                    65.5.0
snowballstemmer               2.2.0
Sphinx                        4.5.0
sphinxcontrib-applehelp       1.0.2
sphinxcontrib-devhelp         1.0.2
sphinxcontrib-htmlhelp        2.0.0
sphinxcontrib-jsmath          1.0.1
sphinxcontrib-qthelp          1.0.3
sphinxcontrib-serializinghtml 1.1.5
typing_extensions             4.4.0
urllib3                       1.26.13
wheel                         0.38.4
```

**Comment by n-peugnet** [comment]
It seems the issue only comes from this assert whose `AssertionError` is not catched : https://github.com/executablebooks/MyST-Parser/blob/c2f041632825ffe9837ebdded4ed324d4288cfa7/myst_parser/config/main.py#L404

From what I can see this assert is unneeded as the same check is performed just after on this line : https://github.com/executablebooks/MyST-Parser/blob/c2f041632825ffe9837ebdded4ed324d4288cfa7/myst_parser/config/main.py#L407-L408

I tested to comment it out and everything worked as expected.
